# Generated by Django 4.2.1 on 2024-09-09 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('intranet', '0003_alter_document_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Qips',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=500)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='qips_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"intranet"."qips"',
            },
        ),
        migrations.CreateModel(
            name='QipsCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=500)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': '"intranet"."qips_category"',
            },
        ),
        migrations.CreateModel(
            name='QipsSubTopic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sub_topic', models.CharField(max_length=500)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('qips', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='qips_topic', to='intranet.qips')),
            ],
            options={
                'db_table': '"intranet"."qips_sub_topic"',
            },
        ),
        migrations.CreateModel(
            name='QipsDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document', models.FileField(upload_to='documents/intranet/qips')),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('original_file_name', models.CharField(max_length=500)),
                ('downloads', models.IntegerField(default=0)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='qips_category_document', to='intranet.qipscategory')),
                ('qips', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='qips_document', to='intranet.qips')),
                ('qips_sub_topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='qips_subtopic_document', to='intranet.qipssubtopic')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='qips_document_uploaded_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"intranet"."qips_documents"',
            },
        ),
        migrations.AddField(
            model_name='qipscategory',
            name='sub_topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='qips_sub_topic', to='intranet.qipssubtopic'),
        ),
    ]
