# Generated by Django 4.2.1 on 2024-09-12 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0004_qips_qipscategory_qipssubtopic_qipsdocument_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='qipsdocument',
            old_name='original_file_name',
            new_name='file_name',
        ),
        migrations.RenameField(
            model_name='qipsdocument',
            old_name='qips_sub_topic',
            new_name='sub_topic',
        ),
        migrations.RenameField(
            model_name='qipsdocument',
            old_name='qips',
            new_name='topic',
        ),
        migrations.RemoveField(
            model_name='qipsdocument',
            name='title',
        ),
    ]
