# Generated by Django 4.2.1 on 2024-09-13 11:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0006_subdepartment_subdepartmentcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='intranet_document_category', to='intranet.subdepartmentcategory'),
        ),
        migrations.AddField(
            model_name='document',
            name='sub_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='intranet_document_sub_department', to='intranet.subdepartment'),
        ),
    ]
