# Generated by Django 4.2.1 on 2024-09-17 09:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('intranet', '0007_document_category_document_sub_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=500)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='survey_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"intranet"."survey"',
            },
        ),
        migrations.CreateModel(
            name='SurveyCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=500)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('sub_topic', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='survey_sub_topic', to='intranet.qipssubtopic')),
            ],
            options={
                'db_table': '"intranet"."survey_category"',
            },
        ),
        migrations.CreateModel(
            name='SurveySubTopic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sub_topic', models.CharField(max_length=500)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('qips', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='survey_topic', to='intranet.survey')),
            ],
            options={
                'db_table': '"intranet"."survey_sub_topic"',
            },
        ),
        migrations.CreateModel(
            name='SurveyLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('link', models.URLField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='survey_category_link', to='intranet.surveycategory')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='survey_link_created_by', to=settings.AUTH_USER_MODEL)),
                ('sub_topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='survey_subtopic_link', to='intranet.surveysubtopic')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='survey_link', to='intranet.survey')),
            ],
            options={
                'db_table': '"intranet"."survey_links"',
            },
        ),
    ]
