# Generated by Django 4.2.1 on 2024-09-17 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0008_survey_surveycategory_surveysubtopic_surveylink'),
    ]

    operations = [
        migrations.RenameField(
            model_name='surveysubtopic',
            old_name='qips',
            new_name='survey',
        ),
    ]
