# Generated by Django 4.2.1 on 2024-09-17 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0009_rename_qips_surveysubtopic_survey'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='surveycategory',
            name='sub_topic',
        ),
    ]
