# Generated by Django 4.2.1 on 2024-09-17 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0010_remove_surveycategory_sub_topic'),
    ]

    operations = [
        migrations.AddField(
            model_name='surveycategory',
            name='sub_topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='survey_sub_topic', to='intranet.surveysubtopic'),
        ),
    ]
