# Generated by Django 4.2.1 on 2024-11-26 09:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('intranet', '0011_surveycategory_sub_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=500)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='modules_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"intranet"."modules"',
            },
        ),
        migrations.CreateModel(
            name='ModuleCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=500)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': '"intranet"."module_categories"',
            },
        ),
        migrations.CreateModel(
            name='ModuleSubTopic',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('sub_topic', models.CharField(max_length=500)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='module_topic', to='intranet.module')),
            ],
            options={
                'db_table': '"intranet"."module_sub_topics"',
            },
        ),
        migrations.CreateModel(
            name='ModuleLink',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('link', models.URLField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='module_category_link', to='intranet.modulecategory')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='module_link_created_by', to=settings.AUTH_USER_MODEL)),
                ('sub_topic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='module_subtopic_link', to='intranet.modulesubtopic')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='module_link', to='intranet.module')),
            ],
            options={
                'db_table': '"intranet"."module_links"',
            },
        ),
        migrations.AddField(
            model_name='modulecategory',
            name='sub_topic',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='module_sub_topic', to='intranet.modulesubtopic'),
        ),
    ]
