# Generated by Django 4.2.1 on 2024-11-27 07:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('intranet', '0012_module_modulecategory_modulesubtopic_modulelink_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneralDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document', models.FileField(upload_to='documents/intranet')),
                ('title', models.CharField(max_length=500)),
                ('file_name', models.CharField(max_length=500)),
                ('is_quick_link', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='general_document_uploaded_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"intranet"."general_documents"',
            },
        ),
    ]
