# Generated by Django 4.2.1 on 2024-11-27 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0013_generaldocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='quicklink',
            name='general_document',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='general_document', to='intranet.generaldocument'),
        ),
    ]
