# Generated by Django 4.2.1 on 2024-11-28 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0015_generaldocument_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='quicklink',
            name='link_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
