# Generated by Django 4.2.1 on 2024-11-28 09:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0016_quicklink_link_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quicklink',
            name='link_type',
        ),
    ]
