# Generated by Django 4.2.1 on 2024-11-28 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0017_remove_quicklink_link_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='quicklink',
            name='link_type',
            field=models.CharField(default='SINGLE', max_length=50),
        ),
    ]
