# Generated by Django 4.2.1 on 2024-11-28 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0018_quicklink_link_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='generaldocument',
            name='downloads',
            field=models.IntegerField(default=0),
        ),
    ]
