# Generated by Django 4.2.1 on 2025-06-19 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0019_generaldocument_downloads'),
    ]

    operations = [
        migrations.AddField(
            model_name='subdepartment',
            name='is_privileges',
            field=models.BooleanField(default=False),
        ),
    ]
