# Generated by Django 4.2.1 on 2025-09-29 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0020_subdepartment_is_privileges'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='document',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='generaldocument',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='generaldocument',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='qipsdocument',
            name='date_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='qipsdocument',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
