# Generated by Django 4.2.1 on 2025-10-13 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0022_platformadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='generaldocument',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='qipsdocument',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
