# Generated by Django 4.2.1 on 2025-10-13 08:14

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('intranet', '0023_document_is_expired_generaldocument_is_expired_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipients', models.JSONField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='document_model', to='intranet.document')),
                ('general_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='general_document_model', to='intranet.generaldocument')),
                ('qips_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='qips_document_model', to='intranet.qipsdocument')),
            ],
            options={
                'db_table': '"intranet"."track_notifications"',
            },
        ),
    ]
