# Generated by Django 4.2.1 on 2025-10-28 05:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('acl', '0022_user_cadre_user_systemusers_cadre_a04bb3_idx'),
        ('intranet', '0024_tracknotification'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrivilegeSubDepartment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='privilege_sub_department_created_by', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='privilege_srrs_main_department', to='acl.srrsdepartment')),
            ],
            options={
                'db_table': '"intranet"."privilege_sub_departments"',
            },
        ),
        migrations.CreateModel(
            name='PrivilegeSubDepartmentCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='privilege_category_created_by', to=settings.AUTH_USER_MODEL)),
                ('sub_department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='privilege_sub_department', to='intranet.privilegesubdepartment')),
            ],
            options={
                'db_table': '"intranet"."privilege_sub_department_categories"',
            },
        ),
        migrations.CreateModel(
            name='PrivilegeDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document', models.FileField(upload_to='documents/intranet/privileges')),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('original_file_name', models.CharField(max_length=500)),
                ('downloads', models.IntegerField(default=0)),
                ('expiry_date', models.DateField(blank=True, null=True)),
                ('is_expired', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='intranet_privilege_document_category', to='intranet.privilegesubdepartmentcategory')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='intranet_privilege_document_department', to='acl.srrsdepartment')),
                ('sub_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='intranet_privilege_document_sub_department', to='intranet.privilegesubdepartment')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='privilege_document_uploaded_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"intranet"."privilege_documents"',
            },
        ),
    ]
