# Generated by Django 4.2.1 on 2024-10-30 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemRecoveryVerification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('module_verified', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('comments', models.TextField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('verified_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='verified_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"db_manager"."system_recovery_verifications"',
            },
        ),
        migrations.CreateModel(
            name='RemoteBackupLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('remote_location', models.CharField(max_length=500)),
                ('size', models.IntegerField(default=0)),
                ('unit', models.CharField(max_length=100)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='remote_log_added_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"db_manager"."remote_backup_logs"',
            },
        ),
        migrations.CreateModel(
            name='BackupLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=500)),
                ('date', models.DateField()),
                ('status', models.CharField(max_length=100)),
                ('size', models.IntegerField(default=0)),
                ('unit', models.CharField(max_length=100)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('action_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='log_added_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"db_manager"."backup_logs"',
            },
        ),
    ]
