# Generated by Django 4.2.1 on 2024-10-31 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbmanager', '0002_remotelocations_system'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='backuplog',
            name='type',
        ),
    ]
