# Generated by Django 4.2.1 on 2024-10-31 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbmanager', '0003_remove_backuplog_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='backuplog',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='system_log_added_by', to='dbmanager.system'),
        ),
    ]
