# Generated by Django 4.2.1 on 2024-10-31 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbmanager', '0004_backuplog_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remotebackuplog',
            name='type',
        ),
    ]
