# Generated by Django 4.2.1 on 2024-10-31 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbmanager', '0006_remotebackuplog_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remotebackuplog',
            name='remote_location',
        ),
    ]
