# Generated by Django 4.2.1 on 2024-10-31 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dbmanager', '0007_remove_remotebackuplog_remote_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='remotebackuplog',
            name='remote_location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='remote_location_added_by', to='dbmanager.remotelocations'),
        ),
    ]
