# Generated by Django 4.2.1 on 2024-11-04 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbmanager', '0008_remotebackuplog_remote_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='backuplog',
            name='size',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='remotebackuplog',
            name='size',
            field=models.FloatField(default=0.0),
        ),
    ]
