# Generated by Django 4.2.1 on 2024-11-15 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbmanager', '0009_alter_backuplog_size_alter_remotebackuplog_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='systemrecoveryverification',
            name='verified_by',
        ),
    ]
