# Generated by Django 4.2.1 on 2024-11-15 06:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dbmanager', '0010_remove_systemrecoveryverification_verified_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemrecoveryverification',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='verified_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='systemrecoveryverification',
            name='verified_by',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
