# Generated by Django 4.2.1 on 2025-04-24 08:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ict_helpdesk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignees',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ict_issue_assigned_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='assignees',
            name='assignee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ict_issue_assignee', to=settings.AUTH_USER_MODEL),
        ),
    ]
