# Generated by Django 4.2.1 on 2025-08-13 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ict_helpdesk', '0003_equipmenttype'),
    ]

    operations = [
        migrations.AddField(
            model_name='priority',
            name='numbering',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
