# Generated by Django 4.2.1 on 2025-08-13 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ict_helpdesk', '0004_priority_numbering'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='priority',
            options={'ordering': ['numbering']},
        ),
    ]
