# Generated by Django 4.2.1 on 2025-09-08 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ict_helpdesk', '0005_alter_priority_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='telephone',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
