# Generated by Django 4.2.1 on 2025-09-11 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ict_helpdesk', '0006_issue_telephone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document', models.FileField(upload_to='documents/ict_helpdesk/uploads/')),
                ('file_name', models.CharField(max_length=500)),
                ('file_type', models.CharField(max_length=255)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ticket_documents', to='ict_helpdesk.issue')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ticket_document_uploaded_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"ict_helpdesk"."documents"',
                'indexes': [models.Index(fields=['issue'], name='documents_issue_i_f25fef_idx')],
            },
        ),
    ]
