# Generated by Django 4.2.1 on 2025-02-10 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhs', '0002_alter_issue_assigned_to_alter_issue_closed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
