# Generated by Django 4.2.1 on 2025-02-10 07:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mhs', '0003_issue_email_issue_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statuschange',
            name='action_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='mhs_action_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
