# Generated by Django 4.2.1 on 2025-02-12 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acl', '0017_sendmail_is_html'),
        ('mhs', '0004_alter_statuschange_action_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='srrs_mhs_department', to='acl.srrsdepartment'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='equipment_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='mhs_equipment_type', to='mhs.equipmenttype'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='job_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='mhs_job_type', to='mhs.jobtype'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='mhs_section', to='mhs.section'),
        ),
    ]
