# Generated by Django 4.2.1 on 2025-02-12 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mhs', '0006_facility'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='mhs_facility', to='mhs.facility'),
        ),
    ]
