# Generated by Django 4.2.1 on 2025-02-17 06:12

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mhs', '0007_issue_facility'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': '"mhs"."categories"',
            },
        ),
    ]
