# Generated by Django 4.2.1 on 2025-02-17 08:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mhs', '0008_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='mhs_category', to='mhs.category'),
        ),
    ]
