# Generated by Django 4.2.1 on 2025-02-17 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhs', '0009_issue_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='is_acknowledged',
            field=models.BooleanField(default=False),
        ),
    ]
