# Generated by Django 4.2.1 on 2025-03-19 10:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('acl', '0017_sendmail_is_html'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(default='REQUESTED', max_length=255)),
                ('location_of_function', models.CharField(max_length=500)),
                ('date_of_event', models.DateField()),
                ('number_of_participants', models.IntegerField()),
                ('am_tea', models.JSONField(blank=True, null=True)),
                ('pm_tea', models.JSONField(blank=True, null=True)),
                ('lunch', models.JSONField(blank=True, null=True)),
                ('dinner', models.JSONField(blank=True, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_closed', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='meal_created_by', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='srrs_smr_department', to='acl.srrsdepartment')),
                ('slt', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='meal_slt', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"smr"."meals"',
            },
        ),
        migrations.CreateModel(
            name='StatusChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=255)),
                ('status_for', models.CharField(blank=True, max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('action_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='smr_action_by', to=settings.AUTH_USER_MODEL)),
                ('meal', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='status_change_issue_instance', to='smr.meal')),
            ],
            options={
                'db_table': '"smr"."status_changes"',
            },
        ),
        migrations.CreateModel(
            name='PlatformAdmin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='ACTIVE', max_length=255)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='smr_admin', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='smr_admin_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"smr"."platform_admins"',
            },
        ),
    ]
