# Generated by Django 4.2.1 on 2025-03-20 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='meals',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
