# Generated by Django 4.2.1 on 2025-04-11 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smr', '0002_meal_meals'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
