# Generated by Django 4.2.1 on 2025-05-27 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smr', '0003_meal_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='total_cost',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
