# Generated by Django 4.2.1 on 2024-11-20 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='affected_person_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
