# Generated by Django 4.2.1 on 2024-11-20 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0002_incident_affected_person_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incident',
            name='location',
        ),
    ]
