# Generated by Django 4.2.1 on 2024-11-20 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acl', '0016_srrsdepartment_hr_partner'),
        ('fms', '0003_remove_incident_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='srrs_fms_sub_department', to='acl.subdepartment'),
        ),
    ]
