# Generated by Django 4.2.1 on 2024-11-21 09:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fms', '0004_incident_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='assignee_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fms_assigned_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
