# Generated by Django 4.2.1 on 2024-12-06 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fms', '0007_platformadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='email',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
