# Generated by Django 4.2.1 on 2024-12-06 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fms', '0008_incident_email_incident_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statuschange',
            name='action_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='fms_action_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
