# Generated by Django 4.2.1 on 2024-06-14 09:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('srrs', '0017_employee_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Access',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(default='REQUESTED', max_length=255)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='asa_employee', to='srrs.employee')),
                ('granted_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='asa_granted_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"asa"."access"',
            },
        ),
        migrations.CreateModel(
            name='StatusChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=255)),
                ('status_for', models.CharField(blank=True, max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('access', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='status_change_access_instance', to='asa.access')),
                ('action_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='asa_action_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"asa"."status_change"',
            },
        ),
    ]
