# Generated by Django 4.2.1 on 2024-07-02 09:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('acl', '0010_alter_user_srrs_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=500)),
                ('employee_no', models.CharField(max_length=255, unique=True)),
                ('employee_type', models.CharField(max_length=255)),
                ('contract_expire_date', models.DateField(blank=True, null=True)),
                ('warehouse', models.CharField(blank=True, max_length=500, null=True)),
                ('status', models.CharField(default='ACTIVE', max_length=255)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='asa_employee_department', to='acl.srrsdepartment')),
            ],
            options={
                'db_table': '"asa"."employees"',
            },
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': '"asa"."systems"',
            },
        ),
        migrations.RemoveField(
            model_name='access',
            name='uid',
        ),
        migrations.AddField(
            model_name='access',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='asa_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='access',
            name='is_hod_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='access',
            name='is_ict_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='access',
            name='granted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='asa_granted_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='SystemAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='asa_employee_system_access', to='asa.employee')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='asa_system', to='asa.system')),
            ],
            options={
                'db_table': '"asa"."system_access"',
            },
        ),
        migrations.CreateModel(
            name='ModuleAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('modules', models.JSONField()),
                ('training_required', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='asa_module_employee', to='asa.employee')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='asa_system_module', to='asa.system')),
            ],
            options={
                'db_table': '"asa"."module_access"',
            },
        ),
        migrations.CreateModel(
            name='DoctorInfo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=255)),
                ('specialty', models.CharField(max_length=255)),
                ('admitting_rights', models.CharField(max_length=255)),
                ('pc_rate', models.CharField(blank=True, max_length=255, null=True)),
                ('clinic', models.CharField(max_length=255)),
                ('services', models.JSONField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='asa_employee_doctor_info', to='asa.employee')),
            ],
            options={
                'db_table': '"asa"."doctor_info"',
            },
        ),
        migrations.AlterField(
            model_name='access',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='asa_employee', to='asa.employee'),
        ),
    ]
