# Generated by Django 4.2.1 on 2024-07-03 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asa', '0002_employee_system_remove_access_uid_access_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moduleaccess',
            name='system',
        ),
    ]
