# Generated by Django 4.2.1 on 2024-07-03 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asa', '0003_remove_moduleaccess_system'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moduleaccess',
            name='training_required',
        ),
    ]
