# Generated by Django 4.2.1 on 2024-07-03 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asa', '0004_remove_moduleaccess_training_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_doctor',
            field=models.CharField(default='NO', max_length=255),
        ),
    ]
