# Generated by Django 4.2.1 on 2024-07-03 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asa', '0005_employee_is_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='is_doctor',
        ),
    ]
