# Generated by Django 4.2.1 on 2024-07-03 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asa', '0006_remove_employee_is_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_doctor',
            field=models.BooleanField(default=False),
        ),
    ]
