# Generated by Django 4.2.1 on 2024-07-03 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asa', '0007_employee_is_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='access',
            name='employee',
        ),
    ]
