# Generated by Django 4.2.1 on 2024-07-03 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asa', '0008_remove_access_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='access',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='asa_employee', to='asa.employee'),
        ),
    ]
