# Generated by Django 4.2.1 on 2024-07-03 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asa', '0009_access_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(default='REQUESTED', max_length=255),
        ),
    ]
