# Generated by Django 4.2.1 on 2024-07-04 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asa', '0010_alter_employee_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='status',
            field=models.CharField(default='INACTIVE', max_length=255),
        ),
    ]
