# Generated by Django 4.2.1 on 2024-07-05 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asa', '0011_alter_employee_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestApprover',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='ACTIVE', max_length=255)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='asa_request_approver', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='asa_approver_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"asa"."approvers"',
            },
        ),
    ]
