# Generated by Django 4.2.1 on 2024-07-10 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asa', '0012_requestapprover'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='signature',
            field=models.TextField(blank=True, null=True),
        ),
    ]
