# Generated by Django 4.2.1 on 2024-07-25 09:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asa', '0013_employee_signature'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.JSONField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='asa_employee_history', to='asa.employee')),
                ('triggered_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='action_triggered_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"asa"."request_history"',
            },
        ),
    ]
