# Generated by Django 4.2.1 on 2024-08-12 10:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asa', '0014_requesthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='access',
            name='agreement_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='access',
            name='agreement_details',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='access',
            name='created_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='asa_created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='access',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='asa_created_for', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='access',
            name='status',
            field=models.CharField(default='PENDING', max_length=255),
        ),
    ]
