# Generated by Django 4.2.1 on 2024-08-21 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asa', '0015_access_agreement_accepted_access_agreement_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduleaccess',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
