# Generated by Django 4.2.1 on 2024-08-21 10:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('asa', '0016_moduleaccess_remarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalSystemAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='asa_additional_employee_system_access', to='asa.employee')),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='asa_additional_system', to='asa.system')),
            ],
            options={
                'db_table': '"asa"."additional_system_access"',
            },
        ),
        migrations.CreateModel(
            name='AdditionalModuleAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('modules', models.JSONField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='asa_additional_module_employee', to='asa.employee')),
            ],
            options={
                'db_table': '"asa"."additional_module_access"',
            },
        ),
    ]
