# Generated by Django 4.2.1 on 2024-08-28 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asa', '0017_additionalsystemaccess_additionalmoduleaccess'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalmoduleaccess',
            name='status',
            field=models.CharField(default='REQUESTED', max_length=20),
        ),
        migrations.AddField(
            model_name='additionalsystemaccess',
            name='status',
            field=models.CharField(default='REQUESTED', max_length=20),
        ),
    ]
