# Generated by Django 4.2.1 on 2025-01-21 10:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('asa', '0020_roles'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoleAccess',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('roles', models.JSONField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='asa_role_employee', to='asa.employee')),
            ],
            options={
                'db_table': '"asa"."role_access"',
            },
        ),
    ]
