# Generated by Django 4.2.1 on 2025-01-22 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asa', '0021_roleaccess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statuschange',
            name='status_for',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
