# Generated by Django 4.2.1 on 2025-01-28 09:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asa', '0022_alter_statuschange_status_for'),
    ]

    operations = [
        migrations.CreateModel(
            name='VerificationStatusChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=255)),
                ('status_for', models.CharField(blank=True, max_length=500, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('access', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='asa_status_change_access_instance', to='asa.access')),
                ('action_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='verification_action_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"asa"."verifications_status_change"',
            },
        ),
        migrations.CreateModel(
            name='Verifications',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_hod_verified', models.BooleanField(default=False)),
                ('is_ict_verified', models.BooleanField(default=False)),
                ('hod_status', models.CharField(max_length=255)),
                ('ict_status', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('access', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='asa_access', to='asa.access')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='asa_access_created_for', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"asa"."verifications"',
            },
        ),
    ]
