# Generated by Django 4.2.1 on 2025-02-03 13:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asa', '0023_verificationstatuschange_verifications'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('request', models.JSONField()),
                ('is_approved', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='asa_new_request_employee', to='asa.employee')),
                ('request_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='requested_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"asa"."new_requests"',
            },
        ),
    ]
