# Generated by Django 4.2.1 on 2025-10-14 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asa', '0024_newrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='newrequest',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
