# Generated by Django 4.2.1 on 2025-10-14 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asa', '0025_newrequest_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='newrequest',
            name='status',
            field=models.CharField(default='PENDING', max_length=50),
        ),
    ]
