# Generated by Django 4.2.1 on 2025-02-03 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='expiry_out',
            new_name='expiry_date',
        ),
    ]
