# Generated by Django 4.2.1 on 2025-08-15 09:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0006_platformadmin'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipients', models.JSONField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='contract_model', to='cms.contract')),
            ],
            options={
                'db_table': '"cms"."track_notifications"',
            },
        ),
    ]
