# Generated by Django 4.2.1 on 2023-05-25 08:35

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'departments',
            },
        ),
        migrations.CreateModel(
            name='Overseer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'overseers',
            },
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'sectors',
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'Titles',
            },
        ),
        migrations.CreateModel(
            name='ThematicArea',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('area', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='thematic_area_department', to='api.department')),
                ('results_leader', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='results_leader', to='api.overseer')),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='thematic_area_sector', to='api.sector')),
                ('strategic_leader', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='strategic_leader', to='api.overseer')),
                ('team_leader', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='team_leader', to='api.overseer')),
            ],
            options={
                'db_table': 'thematic_areas',
            },
        ),
        migrations.CreateModel(
            name='TeamMembers',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('thematic_area', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='member_thematic_area', to='api.thematicarea')),
            ],
            options={
                'db_table': 'team_members',
            },
        ),
        migrations.CreateModel(
            name='RRIGoals',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('goal', models.TextField()),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('thematic_area', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='thematic_area', to='api.thematicarea')),
            ],
            options={
                'db_table': 'rri_goals',
            },
        ),
        migrations.AddField(
            model_name='overseer',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='overseer_title', to='api.title'),
        ),
    ]
