# Generated by Django 4.2.1 on 2023-05-29 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_achievement_achievementdocuments'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='category',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
