# Generated by Django 4.2.1 on 2023-05-29 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_achievement_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievementdocuments',
            name='file_type',
            field=models.CharField(default='FILE', max_length=50),
        ),
    ]
