# Generated by Django 4.2.1 on 2023-06-21 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0006_wave'),
    ]

    operations = [
        migrations.AddField(
            model_name='wave',
            name='lead_coach',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='wave_lead_coach', to=settings.AUTH_USER_MODEL),
        ),
    ]
