# Generated by Django 4.2.1 on 2023-06-21 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_wave_lead_coach'),
    ]

    operations = [
        migrations.AddField(
            model_name='rrigoals',
            name='wave',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='wave', to='api.wave'),
        ),
    ]
