# Generated by Django 4.2.1 on 2023-06-23 17:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0008_rrigoals_wave'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyReports',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('milestone', models.CharField(max_length=50)),
                ('steps', models.JSONField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='weekly_report_creator', to=settings.AUTH_USER_MODEL)),
                ('thematic_area', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='weekly_report_thematic_area', to='api.thematicarea')),
            ],
            options={
                'db_table': 'weekly_reports',
            },
        ),
    ]
