# Generated by Django 4.2.1 on 2023-06-23 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_weeklyreports'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklyreports',
            name='thematic_area',
        ),
        migrations.AddField(
            model_name='weeklyreports',
            name='rri_goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='weekly_report_rri_goal', to='api.rrigoals'),
        ),
    ]
