# Generated by Django 4.2.1 on 2023-06-24 10:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0010_remove_weeklyreports_thematic_area_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkPlan',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('milestone', models.CharField(max_length=50)),
                ('steps', models.JSONField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('person_incharge', models.CharField(max_length=50)),
                ('budget', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('remarks', models.TextField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='work_plan_creator', to=settings.AUTH_USER_MODEL)),
                ('rri_goal', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='work_plan_rri_goal', to='api.rrigoals')),
            ],
            options={
                'db_table': 'workplans',
            },
        ),
    ]
