# Generated by Django 4.2.1 on 2023-06-24 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_workplan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workplan',
            name='person_incharge',
        ),
    ]
