# Generated by Django 4.2.1 on 2023-06-24 10:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0012_remove_workplan_person_incharge'),
    ]

    operations = [
        migrations.AddField(
            model_name='workplan',
            name='person_incharge',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='work_plan_person_incharge', to=settings.AUTH_USER_MODEL),
        ),
    ]
