# Generated by Django 4.2.1 on 2023-06-24 12:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0013_workplan_person_incharge'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultChain',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activities', models.JSONField()),
                ('input', models.TextField()),
                ('output', models.TextField()),
                ('outcome', models.TextField()),
                ('impact', models.TextField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='result_chain_creator', to=settings.AUTH_USER_MODEL)),
                ('rri_goal', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='result_chain_rri_goal', to='api.rrigoals')),
            ],
            options={
                'db_table': 'result_chain',
            },
        ),
    ]
