# Generated by Django 4.2.1 on 2023-06-27 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_resultchain'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammembers',
            name='thematic_area',
        ),
        migrations.RemoveField(
            model_name='thematicarea',
            name='results_leader',
        ),
        migrations.RemoveField(
            model_name='thematicarea',
            name='strategic_leader',
        ),
        migrations.RemoveField(
            model_name='thematicarea',
            name='team_leader',
        ),
        migrations.AddField(
            model_name='rrigoals',
            name='results_leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='results_leader', to='api.overseer'),
        ),
        migrations.AddField(
            model_name='rrigoals',
            name='strategic_leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='strategic_leader', to='api.overseer'),
        ),
        migrations.AddField(
            model_name='rrigoals',
            name='team_leader',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='team_leader', to='api.overseer'),
        ),
        migrations.AddField(
            model_name='teammembers',
            name='goal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='member_goal', to='api.rrigoals'),
        ),
    ]
