# Generated by Django 4.2.1 on 2023-06-27 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_remove_teammembers_thematic_area_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='thematicarea',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
