# Generated by Django 4.2.1 on 2023-06-29 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_thematicarea_is_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resultchain',
            name='impact',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='resultchain',
            name='input',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='resultchain',
            name='outcome',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='resultchain',
            name='output',
            field=models.JSONField(),
        ),
    ]
