# Generated by Django 4.2.1 on 2023-08-03 08:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0018_evaluation'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedEvaluations',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_evaluated', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('evaluator', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='assigned_evaluator', to=settings.AUTH_USER_MODEL)),
                ('rri_goal', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='assigned_rri_goal', to='api.rrigoals')),
            ],
            options={
                'db_table': 'assigned_evaluations',
            },
        ),
    ]
