# Generated by Django 4.2.1 on 2023-08-22 13:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_assignedevaluations'),
    ]

    operations = [
        migrations.AddField(
            model_name='workplan',
            name='percentage',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
