# Generated by Django 4.2.1 on 2023-09-14 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_workplan_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='workplan',
            name='collaborators',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='workplan',
            name='risks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
