# Generated by Django 4.2.1 on 2023-09-16 07:12

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_workplan_collaborators_workplan_risks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Borough',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'boroughs',
            },
        ),
        migrations.CreateModel(
            name='SubCounty',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('borough', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcounties', to='api.borough')),
            ],
            options={
                'db_table': 'sub_counties',
            },
        ),
        migrations.CreateModel(
            name='Ward',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('sub_county', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='wards', to='api.subcounty')),
            ],
            options={
                'db_table': 'wards',
            },
        ),
        migrations.CreateModel(
            name='Estate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('ward', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='estates', to='api.ward')),
            ],
            options={
                'db_table': 'estates',
            },
        ),
    ]
