# Generated by Django 4.2.1 on 2023-09-18 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_borough_subcounty_ward_estate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weeklyreports',
            old_name='steps',
            new_name='data',
        ),
        migrations.RemoveField(
            model_name='weeklyreports',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='weeklyreports',
            name='milestone',
        ),
        migrations.RemoveField(
            model_name='weeklyreports',
            name='rri_goal',
        ),
        migrations.RemoveField(
            model_name='weeklyreports',
            name='start_date',
        ),
        migrations.AddField(
            model_name='weeklyreports',
            name='workplan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='weekly_report_workplan', to='api.workplan'),
        ),
    ]
