# Generated by Django 4.2.1 on 2023-09-18 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_rename_steps_weeklyreports_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workplan',
            name='milestone',
            field=models.CharField(max_length=500),
        ),
    ]
