# Generated by Django 4.2.1 on 2023-09-18 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_alter_workplan_milestone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weeklyreports',
            old_name='data',
            new_name='activities',
        ),
    ]
