# Generated by Django 4.2.1 on 2023-09-19 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_rename_data_weeklyreports_activities'),
    ]

    operations = [
        migrations.AddField(
            model_name='wave',
            name='budget',
            field=models.IntegerField(default=0),
        ),
    ]
