# Generated by Django 4.2.1 on 2023-09-25 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_wave_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='workplan',
            name='location',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
