# Generated by Django 4.2.1 on 2023-09-27 09:33

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0027_workplan_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubSector',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('sector', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sector', to='api.sector')),
            ],
            options={
                'db_table': 'sub_sectors',
            },
        ),
        migrations.CreateModel(
            name='Directorate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('sub_sector', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sub_sector', to='api.subsector')),
            ],
            options={
                'db_table': 'directorates',
            },
        ),
    ]
