# Generated by Django 4.2.1 on 2023-09-28 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_subsector_directorate'),
    ]

    operations = [
        migrations.AddField(
            model_name='wave',
            name='directorate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='wave_directorate', to='api.directorate'),
        ),
        migrations.AddField(
            model_name='wave',
            name='location',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
