# Generated by Django 4.2.1 on 2023-10-12 11:56

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_wave_directorate_wave_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectSubCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'project_sub_categories',
            },
        ),
    ]
