# Generated by Django 4.2.1 on 2023-10-12 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_projectsubcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thematicarea',
            name='department',
        ),
        migrations.AddField(
            model_name='thematicarea',
            name='directorate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='thematic_area_directorate', to='api.directorate'),
        ),
    ]
