# Generated by Django 4.2.1 on 2023-10-12 13:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_remove_thematicarea_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wave',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='wave_sub_category', to='api.projectsubcategory'),
        ),
    ]
