# Generated by Django 4.2.1 on 2023-11-01 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0032_wave_sub_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='wave',
            name='members',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='wave',
            name='mother_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='wave',
            name='type',
            field=models.CharField(default='MAIN', max_length=255),
        ),
    ]
