# Generated by Django 4.2.1 on 2023-11-03 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0034_borough_is_deleted_directorate_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
