# Generated by Django 4.2.1 on 2023-11-03 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_title_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='overseer',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
