# Generated by Django 4.2.1 on 2023-11-04 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_overseer_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='wave',
            name='risks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
