# Generated by Django 4.2.1 on 2023-11-05 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_wave_risks'),
    ]

    operations = [
        migrations.AddField(
            model_name='thematicarea',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='goal_project', to='api.wave'),
        ),
    ]
