# Generated by Django 4.2.1 on 2023-11-05 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0038_thematicarea_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resultchain',
            name='rri_goal',
        ),
        migrations.AddField(
            model_name='resultchain',
            name='workplan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='result_chain_workplan', to='api.workplan'),
        ),
        migrations.AlterField(
            model_name='resultchain',
            name='activities',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
