# Generated by Django 4.2.1 on 2023-11-12 05:23

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0041_remove_wave_lead_coach_wave_results_leaders_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ObjectiveComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=150)),
                ('comment', models.TextField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='comment_goal', to='api.rrigoals')),
            ],
            options={
                'db_table': 'objective_comments',
            },
        ),
    ]
