# Generated by Django 4.2.1 on 2024-08-19 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acl', '0016_srrsdepartment_hr_partner'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('payroll_no', models.CharField(max_length=255)),
                ('supervisor_name', models.CharField(max_length=255)),
                ('time_of_leaving_dept', models.TimeField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sss_created_by', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sss_staff_department', to='acl.srrsdepartment')),
            ],
            options={
                'db_table': '"sls"."staffs"',
            },
        ),
        migrations.CreateModel(
            name='Refer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('consultant_name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sss_refer_staff', to='sls.staff')),
            ],
            options={
                'db_table': '"sls"."refers"',
            },
        ),
        migrations.CreateModel(
            name='Medical',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_fit_to_work', models.BooleanField(default=False)),
                ('days', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('resume_work_on', models.DateField()),
                ('to_be_reviewed_on', models.DateField(blank=True, null=True)),
                ('reason', models.TextField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('staff', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='sss_medical_staff', to='sls.staff')),
            ],
            options={
                'db_table': '"sls"."medical"',
            },
        ),
    ]
