# Generated by Django 4.2.1 on 2024-08-19 12:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sls', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='time_of_leaving_dept',
        ),
    ]
