# Generated by Django 4.2.1 on 2024-08-19 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sls', '0003_remove_medical_is_fit_to_work'),
    ]

    operations = [
        migrations.AddField(
            model_name='medical',
            name='is_fit_to_work',
            field=models.CharField(default='YES'),
        ),
    ]
