# Generated by Django 4.2.1 on 2024-08-20 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sls', '0006_alter_medical_days_alter_medical_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='refer',
            name='consultant_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
