# Generated by Django 4.2.1 on 2024-08-23 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sls', '0009_staff_location_staff_ohc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='location',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='ohc',
        ),
    ]
