# Generated by Django 4.2.1 on 2024-08-23 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acl', '0016_srrsdepartment_hr_partner'),
        ('sls', '0010_remove_staff_location_remove_staff_ohc'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sss_staff_location', to='acl.subdepartment'),
        ),
        migrations.AddField(
            model_name='staff',
            name='ohc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='sss_staff_location_ohc', to='acl.subdepartment'),
        ),
    ]
