# Generated by Django 4.2.1 on 2025-03-26 05:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mhd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformadmin',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='mhs_admin_category', to='mhd.category'),
        ),
        migrations.AddField(
            model_name='platformadmin',
            name='is_hod',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='platformadmin',
            name='is_slt',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Assignees',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='mhd_assignee', to=settings.AUTH_USER_MODEL)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='assignee_issue_instance', to='mhd.issue')),
            ],
            options={
                'db_table': '"mhd"."assignees"',
            },
        ),
    ]
