# Generated by Django 4.2.1 on 2025-03-26 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mhd', '0003_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='priority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='mhs_priority', to='mhd.priority'),
        ),
    ]
