# Generated by Django 4.2.1 on 2025-03-26 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mhd', '0004_issue_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignees',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='mhd_assigned_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
