# Generated by Django 4.2.1 on 2025-03-26 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhd', '0005_assignees_assigned_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='date_assigned',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='date_completed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
