# Generated by Django 4.2.1 on 2025-03-27 02:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhd', '0006_issue_date_assigned_issue_date_completed'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='date_reopened',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
