# Generated by Django 4.2.1 on 2025-03-27 11:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mms', '0009_quote_reasons'),
        ('mhd', '0007_issue_date_reopened'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='quote_issue_instance', to='mhd.issue')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='mmd_quote_issue_instance', to='mms.quote')),
            ],
            options={
                'db_table': '"mhd"."quotes"',
            },
        ),
    ]
