# Generated by Django 4.2.1 on 2025-04-10 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhd', '0008_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='facility',
            name='category',
            field=models.CharField(default='OHC', max_length=255),
        ),
    ]
