# Generated by Django 4.2.1 on 2025-04-10 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhd', '0009_facility_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformadmin',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
