# Generated by Django 4.2.1 on 2025-04-24 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhd', '0010_platformadmin_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='maintenance_type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='request_type',
            field=models.CharField(default='ISSUE', max_length=255),
        ),
    ]
