# Generated by Django 4.2.1 on 2025-04-24 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhd', '0011_issue_maintenance_type_issue_request_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='maintenance_duration',
            field=models.IntegerField(default=0),
        ),
    ]
