# Generated by Django 4.2.1 on 2025-08-18 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mhd', '0012_issue_maintenance_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCard',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('job_card_no', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(default='REQUESTED', max_length=255)),
                ('supplier', models.CharField(blank=True, max_length=200)),
                ('material_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('labour_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('contracted_type', models.CharField(blank=True, max_length=300)),
                ('contracted_to', models.CharField(blank=True, max_length=300)),
                ('lpo_no', models.CharField(blank=True, max_length=100)),
                ('is_hod_approved', models.BooleanField(default=False)),
                ('is_slt_approved', models.BooleanField(default=False)),
                ('is_ceo_approved', models.BooleanField(default=False)),
                ('payments_made_to', models.CharField(blank=True, max_length=300)),
                ('payments_date', models.DateField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='job_card_issue_instance', to='mhd.issue')),
                ('requested_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='job_card_requested_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"mhd"."job_cards"',
            },
        ),
        migrations.CreateModel(
            name='MaterialItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('quantity', models.DecimalField(decimal_places=2, default=1, max_digits=10)),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('job_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='mhd.jobcard')),
            ],
            options={
                'db_table': '"mhd"."job_card_materials"',
            },
        ),
    ]
