# Generated by Django 4.2.1 on 2025-08-18 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mhd', '0013_jobcard_materialitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobcard',
            old_name='contracted_to',
            new_name='contract_to',
        ),
        migrations.RenameField(
            model_name='jobcard',
            old_name='contracted_type',
            new_name='contract_type',
        ),
    ]
