# Generated by Django 4.2.1 on 2025-08-19 14:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mhd', '0014_rename_contracted_to_jobcard_contract_to_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCardStatusChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=255)),
                ('status_for', models.CharField(blank=True, max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('action_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
                ('job_card', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='status_change_job_card_instance', to='mhd.jobcard')),
            ],
            options={
                'db_table': '"mhd"."job_card_status_changes"',
            },
        ),
    ]
