# Generated by Django 4.2.1 on 2025-09-10 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhd', '0015_jobcardstatuschange'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='is_cash_office_approved',
            field=models.BooleanField(default=False),
        ),
    ]
