# Generated by Django 4.2.1 on 2025-09-25 11:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mhd', '0016_jobcard_is_cash_office_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobCardNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note', models.TextField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('job_card', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='note_job_card_instance', to='mhd.jobcard')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='job_card_note_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"mhd"."job_card_notes"',
                'indexes': [models.Index(fields=['job_card'], name='job_card_no_job_car_d078f4_idx'), models.Index(fields=['date_created'], name='job_card_no_date_cr_47feda_idx'), models.Index(fields=['job_card', 'date_created'], name='job_card_no_job_car_59bc3c_idx')],
            },
        ),
        migrations.CreateModel(
            name='JobCardDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document', models.FileField(upload_to='documents/mhd/job_cards/')),
                ('file_name', models.CharField(max_length=500)),
                ('file_type', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('job_card', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='job_card_documents', to='mhd.jobcard')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='job_card_document_uploaded_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"ctp"."job_card_documents"',
                'indexes': [models.Index(fields=['job_card'], name='job_card_do_job_car_c79289_idx'), models.Index(fields=['date_created'], name='job_card_do_date_cr_467e5a_idx'), models.Index(fields=['job_card', 'date_created'], name='job_card_do_job_car_07a9bb_idx')],
            },
        ),
    ]
