# Generated by Django 4.2.1 on 2025-10-07 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mhd', '0017_jobcardnote_jobcarddocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='is_hof_approved',
            field=models.BooleanField(default=False),
        ),
    ]
