# Generated by Django 4.2.1 on 2025-08-21 13:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acl', '0019_trackuser_uid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingMaterial',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=50, unique=True)),
                ('title', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('external_url', models.URLField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='training_created_by', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='training_materials', to='acl.srrsdepartment')),
            ],
            options={
                'db_table': '"ctp"."training_materials"',
            },
        ),
        migrations.CreateModel(
            name='TrainingAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('completion_date', models.DateField(blank=True, null=True)),
                ('date_completed', models.DateField(blank=True, null=True)),
                ('is_completed', models.BooleanField(db_index=True, default=False)),
                ('certificate', models.FileField(blank=True, null=True, upload_to='documents/training/certificates/')),
                ('date_created', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('assigned_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='assignment_by', to=settings.AUTH_USER_MODEL)),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='training_assigned', to='ctp.trainingmaterial')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_assigned', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"ctp"."training_assignments"',
            },
        ),
        migrations.CreateModel(
            name='TrackNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipients', models.JSONField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_model', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"ctp"."track_notifications"',
            },
        ),
        migrations.CreateModel(
            name='PlatformAdmin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='ACTIVE', max_length=255)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ctp_admin', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ctp_admin_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"ctp"."platform_admins"',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document', models.FileField(upload_to='documents/training/courses/')),
                ('file_name', models.CharField(max_length=500)),
                ('file_type', models.CharField(default='training', max_length=255)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='training_documents', to='ctp.trainingmaterial')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='training_document_uploaded_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"ctp"."documents"',
            },
        ),
        migrations.CreateModel(
            name='TrainingResource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('resource_type', models.CharField(db_index=True, max_length=20)),
                ('title', models.CharField(db_index=True, max_length=200)),
                ('url', models.URLField()),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='ctp.trainingmaterial')),
            ],
            options={
                'db_table': '"ctp"."training_recourses"',
                'indexes': [models.Index(fields=['training'], name='training_re_trainin_404153_idx'), models.Index(fields=['resource_type'], name='training_re_resourc_b9d686_idx'), models.Index(fields=['title'], name='training_re_title_970f3b_idx'), models.Index(fields=['training', 'resource_type'], name='training_re_trainin_43da85_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='trainingmaterial',
            index=models.Index(fields=['department'], name='training_ma_departm_0ef0cf_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingmaterial',
            index=models.Index(fields=['title'], name='training_ma_title_cf3d0d_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingmaterial',
            index=models.Index(fields=['created_by'], name='training_ma_created_80b7ac_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingmaterial',
            index=models.Index(fields=['department', 'title'], name='training_ma_departm_3c659e_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingassignment',
            index=models.Index(fields=['user'], name='training_as_user_id_7e5aff_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingassignment',
            index=models.Index(fields=['training'], name='training_as_trainin_965e39_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingassignment',
            index=models.Index(fields=['is_completed'], name='training_as_is_comp_d7edac_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingassignment',
            index=models.Index(fields=['date_created'], name='training_as_date_cr_9b0dde_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingassignment',
            index=models.Index(fields=['user', 'is_completed'], name='training_as_user_id_fbb992_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingassignment',
            index=models.Index(fields=['training', 'is_completed'], name='training_as_trainin_60fb11_idx'),
        ),
        migrations.AddIndex(
            model_name='trainingassignment',
            index=models.Index(fields=['user', 'training', 'is_completed'], name='training_as_user_id_cd3684_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='trainingassignment',
            unique_together={('user', 'training')},
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['training'], name='documents_trainin_bca2b6_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['date_created'], name='documents_date_cr_09256c_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['training', 'date_created'], name='documents_trainin_f55be4_idx'),
        ),
    ]
