# Generated by Django 4.2.1 on 2025-08-21 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingassignment',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainingmaterial',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trainingresource',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
