# Generated by Django 4.2.1 on 2025-08-21 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctp', '0002_trainingassignment_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingmaterial',
            name='type',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='trainingmaterial',
            index=models.Index(fields=['type'], name='training_ma_type_b7eaa0_idx'),
        ),
    ]
