# Generated by Django 4.2.1 on 2025-09-01 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctp', '0003_trainingmaterial_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingmaterial',
            name='category',
            field=models.CharField(blank=True, db_index=True, default='GENERAL', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='trainingassignment',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='trainingmaterial',
            index=models.Index(fields=['category'], name='training_ma_categor_c61cba_idx'),
        ),
    ]
