# Generated by Django 4.2.1 on 2025-10-31 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctp', '0004_trainingmaterial_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingmaterial',
            name='exam_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
