import datetime
import time
from django.db.models import Q
from smr.models import Meal
from django.contrib.auth import get_user_model
from django.core.mail import send_mail, EmailMessage, BadHeaderError
# exec(open('smr/utils/meals.py').read())


from django.utils import timezone
from datetime import timedelta
from string import Template


def read_template(filename):
    with open("acl/emails/" + filename, 'r', encoding='utf8') as template_file:
        template_file_content = template_file.read()
        return Template(template_file_content)

def test_cron():
    timestamp = str(datetime.datetime.now().strftime('%m/%d/%Y, %H:%M:%S'))
    print(f">>> Tested at : [{timestamp}]")

def mark_expired_requests():
    print('--------------Start Expired Requests Fn----------------------')
    today = timezone.now().date()
    
    # Find events that already passed and are not yet marked
    past_events = Meal.objects.filter(date_of_event__lt=today).exclude(Q(status__in=['CEO APPROVED','REJECTED','EXPIRED']))

    # Update their status
    past_events.update(status='EXPIRED')
    

    print(f"{past_events.count()} meals marked as Expired.")
    timestamp = str(datetime.datetime.now().strftime('%m/%d/%Y, %H:%M:%S'))
    print(f">>> Marked at : {timestamp}")
    print('--------------End Expired Requests Fn----------------------')


def mark_approaching_expiry():

    print('--------------Start Approaching Expiry Requests Fn----------------------')
    timestamp = str(datetime.datetime.now().strftime('%m/%d/%Y, %H:%M:%S'))
    print(f"[{timestamp}] Main Fn Starting...")

    start_date = timezone.now().date() + timedelta(days=1)
    end_date = start_date + timedelta(days=1)


    # Filter pending approvals
    slt = Meal.objects.filter(Q(date_of_event__range=(start_date, end_date)) & Q(status__in=['REQUESTED']))
    ceo = Meal.objects.filter(Q(date_of_event__range=(start_date, end_date)) & Q(status__in=['SLT APPROVED']))

    if slt:
        html_main(slt,'SLT')
    if ceo:
        html_main(ceo,'CEO')


    print(f"{slt.count()} meals pending slt approval.")
    print(f"{ceo.count()} meals pending ceo approval.")
    print('--------------End Approaching Expiry Requests Fn----------------------')




def main(meals,target):
    timestamp = str(datetime.datetime.now().strftime('%m/%d/%Y, %H:%M:%S'))
    print(f"[{timestamp}] Main Fn Starting...")


    pending_count = len(meals)

    if target == 'SLT':
        emails = []
        for meal in meals:
            emails.append(meal.department.slt.email)

        
        emails = list(set(emails))

    if target == 'CEO':
        emails = list(get_user_model().objects.filter(Q(groups__name__in=['CEO'])).values_list('email', flat=True))

    subject = "[REMINDER] Pending Meal Requests"
    message = f"""You have meal requests pending approval.\nLog in to Meal Request System to approve.\nVisit: http://172.20.0.42:8010/requests/list\n\nSMR <auto-generated>"""

    try:
        send_mail(subject, message, 'notification@akhskenya.org', emails, fail_silently=False)
        send_mail(subject, message, 'notification@akhskenya.org', ['bobkings.otieno@akhskenya.org'], fail_silently=False)
        print(f'(PLAIN)-<200>-{timestamp}-{str(emails)}')
    except BadHeaderError:
        print(f'(PLAIN)-<400>-{timestamp}-{str(emails)}: Invalid header found.')
    except Exception as e:
        print(f'(PLAIN)-<500>-{timestamp}-An error occurred: {str(e)}')
    
        
    time.sleep(1)

    timestamp = str(datetime.datetime.now().strftime('%m/%d/%Y, %H:%M:%S'))
    print(f">>> Sent at : {timestamp}")


def html_main(meals,target):
    timestamp = str(datetime.datetime.now().strftime('%m/%d/%Y, %H:%M:%S'))
    print(f"[{timestamp}] Main Fn Starting...")

    subject = "[REMINDER] Meal Request Pending Approval"
    message_template = read_template("meals_template.html")

    for meal in meals:
        if target == 'SLT':
            email = meal.department.slt.email
        if target == 'CEO':
            email = list(get_user_model().objects.filter(Q(groups__name__in=['CEO'])).values_list('email', flat=True))[0]

        message = f"""
                    <table class="main" width="100%">
                        <tr>
                            <th style="text-align: left; padding: 6px 0" colspan="5">MEALS DETAILS</th>
                        </tr>
                        <tr>
                            <th style="text-align: left; padding: 5px 0">Request From</th>
                            <td style="text-align: left; padding: 5px 0">{meal.created_by.first_name} {meal.created_by.last_name}</td>
                        </tr>
                        <tr>
                            <th style="text-align: left; padding: 5px 0">Requesting Department</th>
                            <td style="text-align: left; padding: 5px 0">{meal.department.name}</td>
                        </tr>
                        <tr>
                            <th style="text-align: left; padding: 5px 0">Location</th>
                            <td style="text-align: left; padding: 5px 0">{meal.location_of_function}</td>
                        </tr>
                        <tr>
                            <th style="text-align: left; padding: 5px 0">Date of Event</th>
                            <td style="text-align: left; padding: 5px 0">{meal.date_of_event}</td>
                        </tr>
                        <tr>
                            <th style="text-align: left; padding: 5px 0">Event Justification</th>
                            <td style="text-align: left; padding: 5px 0">{meal.reason}</td>
                        </tr>
                        <tr>
                            <th style="text-align: left; padding: 5px 0">Number of Participants</th>
                            <td style="text-align: left; padding: 5px 0">{meal.number_of_participants}</td>
                        </tr>
                        <tr>
                            <th style="text-align: left; padding: 5px 0">AM Tea</th>
                            <td style="text-align: left; padding: 5px 0">
                                <strong>Time: </strong>
                                {meal.am_tea.get('time') or 'N/A'} <br>
                                <strong>Description:</strong><br>
                                {meal.am_tea.get('description') or 'N/A'}                                    
                            </td>
                        </tr>
                        <tr>
                            <th style="text-align: left; padding: 5px 0">Lunch</th>
                            <td style="text-align: left; padding: 5px 0">
                                <strong>Time: </strong>
                                {meal.lunch.get('time') or 'N/A'} <br>
                                <strong>Description:</strong><br>
                                {meal.lunch.get('description') or 'N/A'}
                            </td>
                        </tr>
                        <tr>
                            <th style="text-align: left; padding: 5px 0">PM Tea</th>
                            <td style="text-align: left; padding: 5px 0">
                                <strong>Time: </strong>
                                {meal.pm_tea.get('time') or 'N/A'} <br>
                                <strong>Description:</strong><br>
                                {meal.pm_tea.get('description') or 'N/A'}
                                
                            </td>
                        </tr>
                        <tr>
                            <th style="text-align: left; padding: 5px 0">Dinner</th>
                            <td style="text-align: left; padding: 5px 0">
                                <strong>Time: </strong>
                                {meal.dinner.get('time') or 'N/A'} <br>
                                <strong>Description:</strong><br>
                                {meal.dinner.get('description') or 'N/A'}
                            </td>
                        </tr>
                    </table>
                """
                # uri = f"requests/view/{str(tripInstance.traveler.id)}"
        try:
            
            platform = 'Staff Meal Request'
            uri = f"authentication/auto/{email}/{str(meal.id)}"
            link = "http://172.20.0.42:8010/" + uri
            approve = link + '/approved'
            reject = link + '/rejected'

            msg = message_template.substitute(
                CONTENT=message,
                LINK=link,
                PLATFORM=platform,
                APPROVE=approve,
                REJECT=reject
            )

            email_to_send = EmailMessage(
                subject,
                msg,
                'notification@akhskenya.org',
                [email]
            )
            email_to_send.content_subtype = 'html'  # Set the content type to HTML
            try:
                email_to_send.send(fail_silently=False)
                print(f'(HTML)-<200>-{timestamp}-{str(email)}')
            except Exception as e:
                print(f'(HTML)-<500>-{timestamp}-An error occurred: {str(e)}')

        except Exception as e:
            print(f'(PLAIN)-<500>-{timestamp}-An error occurred: {str(e)}')

    
        
        time.sleep(1)

    timestamp = str(datetime.datetime.now().strftime('%m/%d/%Y, %H:%M:%S'))
    print(f">>> Sent at : {timestamp}")