# Generated by Django 4.2.1 on 2024-05-17 08:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('acl', '0006_alter_department_name_slt_department_slt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recruit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=50, unique=True)),
                ('status', models.CharField(default='REQUESTED', max_length=255)),
                ('position_title', models.CharField(max_length=255)),
                ('position_type', models.CharField(max_length=255)),
                ('qualifications', models.JSONField()),
                ('job_description', models.TextField()),
                ('nature_of_hiring', models.CharField(max_length=255)),
                ('existing_staff_same_title', models.JSONField(blank=True, null=True)),
                ('reasons_for_not_sharing_tasks', models.TextField(blank=True, null=True)),
                ('filling_period_from', models.DateField()),
                ('filling_period_to', models.DateField()),
                ('temporary_task_assignment_to', models.CharField(max_length=255)),
                ('replacement_details', models.JSONField(blank=True, null=True)),
                ('rejection_reasons', models.JSONField(blank=True, null=True)),
                ('proposed_salary', models.BigIntegerField(default=0)),
                ('budget_approval_file', models.FileField(blank=True, null=True, upload_to='documents/srrs/budget_approval/')),
                ('hhr_comments', models.TextField(blank=True, null=True)),
                ('hof_comments', models.TextField(blank=True, null=True)),
                ('ceo_comments', models.TextField(blank=True, null=True)),
                ('is_slt_approved', models.BooleanField(default=False)),
                ('is_hhr_approved', models.BooleanField(default=False)),
                ('is_hof_approved', models.BooleanField(default=False)),
                ('is_ceo_approved', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_closed', models.DateTimeField(blank=True, null=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='srrs_closed_by', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='srrs_created_by', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='srrs_department', to='acl.department')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='srrs_rejected_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"srrs"."recruits"',
            },
        ),
        migrations.CreateModel(
            name='StatusChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=255)),
                ('status_for', models.CharField(blank=True, max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('action_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='srrs_action_by', to=settings.AUTH_USER_MODEL)),
                ('recruit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='status_change_recruit_instance', to='srrs.recruit')),
            ],
            options={
                'db_table': '"srrs"."status_change"',
            },
        ),
        migrations.CreateModel(
            name='RecruitHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=50)),
                ('data', models.JSONField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('triggered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='triggered_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"srrs"."recruit_history"',
            },
        ),
    ]
