# Generated by Django 4.2.1 on 2024-05-20 05:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srrs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruit',
            name='qualifications',
        ),
    ]
