# Generated by Django 4.2.1 on 2024-05-20 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srrs', '0002_remove_recruit_qualifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruit',
            name='qualifications',
            field=models.TextField(blank=True, null=True),
        ),
    ]
