# Generated by Django 4.2.1 on 2024-05-21 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srrs', '0003_recruit_qualifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruit',
            name='slt_comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
