# Generated by Django 4.2.1 on 2024-05-23 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srrs', '0004_recruit_slt_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruit',
            name='filling_period_from',
        ),
        migrations.RemoveField(
            model_name='recruit',
            name='filling_period_to',
        ),
        migrations.RemoveField(
            model_name='recruit',
            name='job_description',
        ),
        migrations.AddField(
            model_name='recruit',
            name='filling_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recruit',
            name='period_from',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='recruit',
            name='period_to',
            field=models.DateField(blank=True, null=True),
        ),
    ]
