# Generated by Django 4.2.1 on 2024-05-23 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srrs', '0005_remove_recruit_filling_period_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruit',
            name='job_description',
            field=models.FileField(blank=True, null=True, upload_to='documents/srrs/job_description/'),
        ),
    ]
