# Generated by Django 4.2.1 on 2024-06-04 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srrs', '0006_recruit_job_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruit',
            name='reporting_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
