# Generated by Django 4.2.1 on 2024-06-04 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('srrs', '0007_recruit_reporting_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocumAttendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('data', models.JSONField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('action_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='attendance_action_by', to=settings.AUTH_USER_MODEL)),
                ('recruit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='attendance_recruit_instance', to='srrs.recruit')),
            ],
            options={
                'db_table': '"srrs"."locum_attendance"',
            },
        ),
    ]
