# Generated by Django 4.2.1 on 2024-06-05 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srrs', '0008_locumattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruit',
            name='reporting_station',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='recruit',
            name='working_station',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
