# Generated by Django 4.2.1 on 2024-06-06 09:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('srrs', '0009_recruit_reporting_station_recruit_working_station'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruit',
            name='reporting_date',
        ),
        migrations.RemoveField(
            model_name='recruit',
            name='reporting_station',
        ),
        migrations.RemoveField(
            model_name='recruit',
            name='working_station',
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('employee_no', models.CharField(max_length=255)),
                ('reporting_date', models.DateField()),
                ('reporting_station', models.CharField(max_length=500)),
                ('working_station', models.CharField(blank=True, max_length=500, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('action_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='employee_action_by', to=settings.AUTH_USER_MODEL)),
                ('recruit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='employee_recruit_instance', to='srrs.recruit')),
            ],
            options={
                'db_table': '"srrs"."employees"',
            },
        ),
    ]
