# Generated by Django 4.2.1 on 2024-06-06 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srrs', '0011_alter_recruit_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='email',
            field=models.EmailField(blank=True, max_length=500, null=True),
        ),
    ]
