# Generated by Django 4.2.1 on 2024-06-06 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srrs', '0012_employee_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recruit',
            name='department',
        ),
    ]
