# Generated by Django 4.2.1 on 2024-06-06 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acl', '0010_alter_user_srrs_department'),
        ('srrs', '0013_remove_recruit_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruit',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='srrs_department', to='acl.srrsdepartment'),
        ),
    ]
