# Generated by Django 4.2.1 on 2024-06-06 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('srrs', '0014_recruit_department'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locumattendance',
            name='recruit',
        ),
    ]
