# Generated by Django 4.2.1 on 2024-06-06 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('srrs', '0015_remove_locumattendance_recruit'),
    ]

    operations = [
        migrations.AddField(
            model_name='locumattendance',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='employee_attendance', to='srrs.employee'),
        ),
    ]
