# Generated by Django 4.2.1 on 2024-06-12 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srrs', '0016_locumattendance_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='status',
            field=models.CharField(default='ACTIVE', max_length=255),
        ),
    ]
