# Generated by Django 4.2.1 on 2024-07-18 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acl', '0014_remove_srrsdepartment_hod'),
        ('srrs', '0017_employee_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruit',
            name='ohc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='srrs_ohc', to='acl.ohc'),
        ),
        migrations.AddField(
            model_name='recruit',
            name='sub_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='srrs_sub_department', to='acl.subdepartment'),
        ),
    ]
