# Generated by Django 4.2.1 on 2024-08-07 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('srrs', '0018_recruit_ohc_recruit_sub_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyLocumAttendance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('hours_worked', models.IntegerField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('action_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='monthly_attendance_action_by', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='employee_monthly_attendance', to='srrs.employee')),
            ],
            options={
                'db_table': '"srrs"."monthly_locum_attendance"',
            },
        ),
    ]
