# Generated by Django 4.2.1 on 2024-08-09 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srrs', '0019_monthlylocumattendance'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruit',
            name='justification',
            field=models.TextField(blank=True, null=True),
        ),
    ]
