# Generated by Django 4.2.1 on 2024-08-13 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('srrs', '0020_recruit_justification'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlylocumattendance',
            name='days_worked',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='monthlylocumattendance',
            name='hours_worked',
            field=models.IntegerField(default=0),
        ),
    ]
