# Generated by Django 4.2.1 on 2024-08-13 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('srrs', '0021_monthlylocumattendance_days_worked_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlylocumattendance',
            name='date_updated',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlylocumattendance',
            name='reason_for_extra_hours',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='monthlylocumattendance',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='monthly_attendance_updated_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
