# Generated by Django 4.2.1 on 2025-06-10 09:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('srrs', '0023_recruit_hr_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='recruit',
            name='preferred_slt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='srrs_preferred_slt', to=settings.AUTH_USER_MODEL),
        ),
    ]
