# Generated by Django 4.2.1 on 2024-03-22 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Traveler',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_no', models.CharField(max_length=50)),
                ('status', models.CharField(default='REQUESTED', max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('tid', models.CharField(max_length=50, unique=True)),
                ('purpose', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('budget_code', models.CharField(blank=True, max_length=255, null=True)),
                ('travel_order_no', models.CharField(blank=True, max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_closed', models.DateTimeField(blank=True, null=True)),
                ('traveler', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='traveler', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"trs"."traveler"',
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('route', models.TextField()),
                ('departure_date', models.DateField()),
                ('return_date', models.DateField()),
                ('accommodation', models.BooleanField(default=False)),
                ('visa_required_date', models.DateField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('traveler', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='traveler_instance', to='trs.traveler')),
            ],
            options={
                'db_table': '"trs"."trip"',
            },
        ),
        migrations.CreateModel(
            name='Costing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cost', models.JSONField()),
                ('accommodation', models.JSONField()),
                ('bill_settlement_by', models.CharField(max_length=255)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='costing_approver', to=settings.AUTH_USER_MODEL)),
                ('traveler', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='costing_traveler_instance', to='trs.traveler')),
            ],
            options={
                'db_table': '"trs"."costings"',
            },
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('approval_for', models.CharField(max_length=255)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='approver', to=settings.AUTH_USER_MODEL)),
                ('traveler', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='approval_traveler_instance', to='trs.traveler')),
            ],
            options={
                'db_table': '"trs"."approvals"',
            },
        ),
    ]
