# Generated by Django 4.2.1 on 2024-05-02 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acl', '0006_alter_department_name_slt_department_slt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Traveler',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_no', models.CharField(blank=True, max_length=50, null=True)),
                ('employees', models.JSONField(blank=True, null=True)),
                ('requesting_for', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(default='REQUESTED', max_length=255)),
                ('type_of_travel', models.CharField(blank=True, max_length=255, null=True)),
                ('mode_of_transport', models.CharField(blank=True, max_length=255, null=True)),
                ('position', models.CharField(blank=True, max_length=255, null=True)),
                ('tid', models.CharField(max_length=50, unique=True)),
                ('purpose', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('budget_code', models.CharField(blank=True, max_length=255, null=True)),
                ('travel_order_no', models.CharField(blank=True, max_length=255, null=True)),
                ('travel_cost', models.BigIntegerField(default=0)),
                ('travel_cost_items', models.JSONField(blank=True, null=True)),
                ('advance_requests', models.JSONField(blank=True, null=True)),
                ('salary_advance_required', models.BooleanField(default=False)),
                ('is_hod_approved', models.BooleanField(default=False)),
                ('is_hof_approved', models.BooleanField(default=False)),
                ('is_slt_approved', models.BooleanField(default=False)),
                ('is_ceo_approved', models.BooleanField(default=False)),
                ('is_transport_dpt_approved', models.BooleanField(default=False)),
                ('is_administrator_approved', models.BooleanField(default=False)),
                ('is_cash_office_approved', models.BooleanField(default=False)),
                ('requires_hod_approval', models.BooleanField(default=False)),
                ('requires_hof_approval', models.BooleanField(default=False)),
                ('requires_slt_approval', models.BooleanField(default=False)),
                ('requires_ceo_approval', models.BooleanField(default=False)),
                ('requires_administrator_approval', models.BooleanField(default=False)),
                ('requires_transport_approval', models.BooleanField(default=False)),
                ('requires_cash_office_approval', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_closed', models.DateTimeField(blank=True, null=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='closed_by', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_by', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='department', to='acl.department')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='rejected_by', to=settings.AUTH_USER_MODEL)),
                ('traveler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='traveler', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"trs"."traveler"',
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('route', models.TextField()),
                ('departure_date', models.DateField()),
                ('return_date', models.DateField()),
                ('accommodation', models.BooleanField(default=False)),
                ('visa_required_date', models.DateField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('traveler', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='traveler_instance', to='trs.traveler')),
            ],
            options={
                'db_table': '"trs"."trip"',
            },
        ),
        migrations.CreateModel(
            name='TravelForwarding',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('forward_from', models.CharField(max_length=255)),
                ('forward_to', models.CharField(max_length=255)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('forward_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='forward_by', to=settings.AUTH_USER_MODEL)),
                ('traveler', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='travel_forwarding_instance', to='trs.traveler')),
            ],
            options={
                'db_table': '"trs"."travel_forwarding"',
            },
        ),
        migrations.CreateModel(
            name='StatusChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=255)),
                ('status_for', models.CharField(blank=True, max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('action_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='action_by', to=settings.AUTH_USER_MODEL)),
                ('traveler', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='status_change_track_instance', to='trs.traveler')),
            ],
            options={
                'db_table': '"trs"."status_change"',
            },
        ),
        migrations.CreateModel(
            name='Costing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cost', models.JSONField()),
                ('accommodation', models.JSONField()),
                ('bill_settlement_by', models.CharField(max_length=255)),
                ('air_ticket', models.FileField(blank=True, null=True, upload_to='documents/air_ticket/')),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='costing_approver', to=settings.AUTH_USER_MODEL)),
                ('traveler', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='costing_traveler_instance', to='trs.traveler')),
            ],
            options={
                'db_table': '"trs"."costings"',
            },
        ),
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('approval_for', models.CharField(max_length=255)),
                ('approval_msg', models.JSONField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='approver', to=settings.AUTH_USER_MODEL)),
                ('traveler', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='approval_traveler_instance', to='trs.traveler')),
            ],
            options={
                'db_table': '"trs"."approvals"',
            },
        ),
        migrations.CreateModel(
            name='AdvanceSalaryRequests',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='REQUESTED', max_length=255)),
                ('amount', models.BigIntegerField(default=0)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='advance_salary_approver', to=settings.AUTH_USER_MODEL)),
                ('traveler', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='advance_salary_requestor', to='trs.traveler')),
            ],
            options={
                'db_table': '"trs"."advance_salary_requests"',
            },
        ),
    ]
