# Generated by Django 4.2.1 on 2024-03-25 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveler',
            name='is_ceo_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='traveler',
            name='is_hod_approved',
            field=models.BooleanField(default=False),
        ),
    ]
