# Generated by Django 4.2.1 on 2024-05-17 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costing',
            name='air_ticket',
            field=models.FileField(blank=True, null=True, upload_to='documents/trs/air_ticket/'),
        ),
    ]
