# Generated by Django 4.2.1 on 2024-03-25 13:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trs', '0002_traveler_is_ceo_approved_traveler_is_hod_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveler',
            name='salary_advance_required',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='AdvanceSalaryRequests',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='REQUESTED', max_length=255)),
                ('amount', models.CharField(max_length=255)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='advance_salary_approver', to=settings.AUTH_USER_MODEL)),
                ('traveler', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='advance_salary_requestor', to='trs.traveler')),
            ],
            options={
                'db_table': '"trs"."advance_salary_requests"',
            },
        ),
    ]
