# Generated by Django 4.2.1 on 2024-07-31 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trs', '0002_alter_costing_air_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='estimated_distance',
            field=models.IntegerField(default=0),
        ),
    ]
