# Generated by Django 4.2.1 on 2024-08-08 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trs', '0003_trip_estimated_distance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traveler',
            name='department',
        ),
    ]
