# Generated by Django 4.2.1 on 2024-03-25 13:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trs', '0003_traveler_salary_advance_required_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancesalaryrequests',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='advance_salary_approver', to=settings.AUTH_USER_MODEL),
        ),
    ]
