# Generated by Django 4.2.1 on 2024-08-08 06:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acl', '0015_otp'),
        ('trs', '0004_remove_traveler_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveler',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='department', to='acl.srrsdepartment'),
        ),
    ]
