# Generated by Django 4.2.1 on 2024-04-02 10:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acl', '0005_user_employee_no'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trs', '0004_alter_advancesalaryrequests_approved_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveler',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='created_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='traveler',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='department', to='acl.department'),
        ),
        migrations.AddField(
            model_name='traveler',
            name='employees',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='traveler',
            name='group',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='traveler',
            name='is_administrator_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='traveler',
            name='is_slt_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='traveler',
            name='is_transport_dpt_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='traveler',
            name='mode_of_transport',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='traveler',
            name='requesting_for',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='traveler',
            name='requires_ceo_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='traveler',
            name='travel_cost',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='traveler',
            name='traveler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='traveler', to=settings.AUTH_USER_MODEL),
        ),
    ]
