# Generated by Django 4.2.1 on 2024-04-02 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trs', '0005_traveler_created_by_traveler_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='traveler',
            name='group',
        ),
        migrations.AlterField(
            model_name='traveler',
            name='employee_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='traveler',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
