# Generated by Django 4.2.1 on 2024-10-03 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trs', '0005_traveler_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='traveler',
            name='travel_cost',
            field=models.BigIntegerField(blank=True, default=0, null=True),
        ),
    ]
