# Generated by Django 4.2.1 on 2024-04-04 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trs', '0006_remove_traveler_group_alter_traveler_employee_no_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveler',
            name='is_hof_approved',
            field=models.BooleanField(default=False),
        ),
    ]
