# Generated by Django 4.2.1 on 2024-10-07 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trs', '0006_alter_traveler_travel_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='departure_time',
            field=models.CharField(blank=True, null=True),
        ),
    ]
