# Generated by Django 4.2.1 on 2024-04-04 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trs', '0007_traveler_is_hof_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveler',
            name='is_cash_office_approved',
            field=models.BooleanField(default=False),
        ),
    ]
