# Generated by Django 4.2.1 on 2024-10-14 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trs', '0007_trip_departure_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveler',
            name='ceo_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='traveler',
            name='hod_comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
