# Generated by Django 4.2.1 on 2024-04-05 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trs', '0008_traveler_is_cash_office_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='approval',
            name='approval_msg',
            field=models.TextField(blank=True, null=True),
        ),
    ]
