# Generated by Django 4.2.1 on 2024-10-14 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trs', '0008_traveler_ceo_comments_traveler_hod_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveler',
            name='rejection_comments',
            field=models.TextField(blank=True, null=True),
        ),
    ]
