# Generated by Django 4.2.1 on 2024-04-05 09:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trs', '0009_approval_approval_msg'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveler',
            name='closed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='closed_by', to=settings.AUTH_USER_MODEL),
        ),
    ]
