# Generated by Django 4.2.1 on 2025-06-14 07:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trs', '0010_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveler',
            name='preferred_hod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='preferred_hod', to=settings.AUTH_USER_MODEL),
        ),
    ]
