# Generated by Django 4.2.1 on 2024-04-09 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trs', '0011_traveler_rejected_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveler',
            name='travel_cost_items',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
