# Generated by Django 4.2.1 on 2024-04-09 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trs', '0012_traveler_travel_cost_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveler',
            name='requires_hod_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='traveler',
            name='requires_hof_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='traveler',
            name='requires_slt_approval',
            field=models.BooleanField(default=False),
        ),
    ]
