# Generated by Django 4.2.1 on 2024-04-11 09:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trs', '0013_traveler_requires_hod_approval_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatusChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=255)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('action_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='action_by', to=settings.AUTH_USER_MODEL)),
                ('traveler', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='status_change_track_instance', to='trs.traveler')),
            ],
            options={
                'db_table': '"trs"."status_change"',
            },
        ),
    ]
