# Generated by Django 4.2.1 on 2024-04-11 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trs', '0014_statuschange'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveler',
            name='requires_administrator_approval',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='traveler',
            name='requires_transport_approval',
            field=models.BooleanField(default=False),
        ),
    ]
