# Generated by Django 4.2.1 on 2024-04-11 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trs', '0015_traveler_requires_administrator_approval_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveler',
            name='requires_cash_office_approval',
            field=models.BooleanField(default=False),
        ),
    ]
