# Generated by Django 4.2.1 on 2024-04-12 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trs', '0017_travelforwarding'),
    ]

    operations = [
        migrations.AddField(
            model_name='statuschange',
            name='status_for',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
