# Generated by Django 4.2.1 on 2024-04-12 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trs', '0018_statuschange_status_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='approval_msg',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
