# Generated by Django 4.2.1 on 2024-04-16 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trs', '0019_alter_approval_approval_msg'),
    ]

    operations = [
        migrations.AddField(
            model_name='costing',
            name='air_ticket',
            field=models.FileField(blank=True, null=True, upload_to='documents/air_ticket/'),
        ),
    ]
