# Generated by Django 4.2.1 on 2024-04-17 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trs', '0020_costing_air_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancesalaryrequests',
            name='amount',
            field=models.BigIntegerField(default=0),
        ),
    ]
