# Generated by Django 4.2.1 on 2024-04-17 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trs', '0021_alter_advancesalaryrequests_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveler',
            name='advance_requests',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
