# Generated by Django 4.2.1 on 2024-04-23 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trs', '0022_traveler_advance_requests'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveler',
            name='type_of_travel',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
