# Generated by Django 4.2.1 on 2024-03-08 08:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('acl', '0002_alter_user_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document', models.FileField(upload_to='mms_documents')),
                ('original_file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(default='FILE', max_length=50)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='document_uploader', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mms_documents',
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('content', models.JSONField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('attachment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='document_attached', to='mms.document')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='from_department', to='acl.department')),
                ('uploader', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='quote_uploader', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'boroughs',
            },
        ),
    ]
