# Generated by Django 4.2.1 on 2024-03-08 14:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mms', '0002_quote_status'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='quote',
            table='quotes',
        ),
        migrations.CreateModel(
            name='QuoteAssignee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='ASSIGNED', max_length=500)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('assigned', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='quote_assignee', to=settings.AUTH_USER_MODEL)),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='quote_assigned', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'quote_assignees',
            },
        ),
    ]
