# Generated by Django 4.2.1 on 2024-03-08 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mms', '0003_alter_quote_table_quoteassignee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoteassignee',
            name='quote',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='quote_assigned', to='mms.quote'),
        ),
    ]
