# Generated by Django 4.2.1 on 2024-03-11 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mms', '0004_alter_quoteassignee_quote'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='title',
            field=models.CharField(default='QUOTE', max_length=255),
        ),
        migrations.AddField(
            model_name='quote',
            name='date_closed',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
