# Generated by Django 4.2.1 on 2024-03-11 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mms', '0005_document_title_quote_date_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='close_attachments',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
