# Generated by Django 4.2.1 on 2024-03-13 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mms', '0006_quote_close_attachments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='attachment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='document_attached', to='mms.document'),
        ),
    ]
