# Generated by Django 4.2.1 on 2024-03-14 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mms', '0007_alter_quote_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='qid',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
