# Generated by Django 4.2.1 on 2024-05-13 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mms', '0008_quote_qid'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='reasons',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
