# Generated by Django 4.2.1 on 2025-10-08 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mms', '0010_note'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
