# Generated by Django 4.2.1 on 2025-05-14 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=50, unique=True)),
                ('admission_no', models.CharField(max_length=255)),
                ('status', models.CharField(default='SUBMITTED', max_length=255)),
                ('illness_severity', models.CharField(max_length=255)),
                ('patient_summary', models.JSONField()),
                ('action_list', models.JSONField()),
                ('situation_awareness', models.JSONField()),
                ('synthesis_by_receiver', models.TextField(blank=True, null=True)),
                ('acknowledgement', models.JSONField(blank=True, null=True)),
                ('bio', models.JSONField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('handover_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='handover_by', to=settings.AUTH_USER_MODEL)),
                ('handover_to', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='handover_to', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"ipass"."patients"',
            },
        ),
        migrations.CreateModel(
            name='StatusChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=255)),
                ('status_for', models.CharField(blank=True, max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('action_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ipass_action_by', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='status_change_patient_instance', to='ipass.patient')),
            ],
            options={
                'db_table': '"ipass"."status_change"',
            },
        ),
        migrations.CreateModel(
            name='PlatformDoctor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='ACTIVE', max_length=255)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ipass_doctor_created_by', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ipass_doctor', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"ipass"."platform_doctors"',
            },
        ),
    ]
