# Generated by Django 4.2.1 on 2025-05-15 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipass', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='handover_acceptance_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
