# Generated by Django 4.2.1 on 2025-05-15 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipass', '0002_patient_handover_acceptance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='status',
            field=models.CharField(default='PENDING', max_length=255),
        ),
    ]
