# Generated by Django 4.2.1 on 2025-06-11 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipass', '0003_alter_patient_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='action_list',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='patient_summary',
            field=models.TextField(blank=True, null=True),
        ),
    ]
