# Generated by Django 4.2.1 on 2025-06-11 08:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ipass', '0004_alter_patient_action_list_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='situation_awareness',
        ),
    ]
