# Generated by Django 4.2.1 on 2025-06-11 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipass', '0005_remove_patient_situation_awareness'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='attestation',
            field=models.BooleanField(default=False),
        ),
    ]
