# Generated by Django 4.2.1 on 2025-07-03 09:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ipass', '0006_patient_attestation'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailExempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ipass_email_exempt_created_by', to=settings.AUTH_USER_MODEL)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ipass_email_exempt', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"ipass"."email_exempts"',
            },
        ),
    ]
