# Generated by Django 4.2.1 on 2025-08-08 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='barcode',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='serial_no',
        ),
    ]
