# Generated by Django 4.2.1 on 2025-08-08 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0002_remove_asset_barcode_remove_asset_serial_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='asset_no',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
