# Generated by Django 4.2.1 on 2025-08-08 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0003_asset_asset_no_asset_category_asset_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asset',
            old_name='data',
            new_name='properties',
        ),
    ]
