# Generated by Django 4.2.1 on 2025-08-08 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ict_helpdesk', '0002_alter_assignees_assigned_by_alter_assignees_assignee'),
        ('ams', '0004_rename_data_asset_properties'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='custodian',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ams_facility', to='ict_helpdesk.facility'),
        ),
        migrations.AddField(
            model_name='asset',
            name='specific_location',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='last_updated',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['asset_no', 'type'], name='assets_asset_n_140fa4_idx'),
        ),
    ]
