# Generated by Django 4.2.1 on 2025-08-08 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0005_asset_custodian_asset_description_asset_facility_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='procurement_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
