# Generated by Django 4.2.1 on 2025-08-27 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ams', '0006_asset_procurement_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='serial_no',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True),
        ),
    ]
