# Generated by Django 4.2.1 on 2025-10-30 08:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('acl', '0022_user_cadre_user_systemusers_cadre_a04bb3_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenditureRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=50, unique=True)),
                ('reference_no', models.CharField(db_index=True, max_length=20, unique=True)),
                ('description', models.TextField()),
                ('invoice_number', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('amount_kes', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(db_index=True, default='REQUESTED', max_length=20)),
                ('is_hod_approved', models.BooleanField(default=False)),
                ('is_finance_manager_approved', models.BooleanField(default=False)),
                ('is_ceo_approved', models.BooleanField(default=False)),
                ('is_hof_approved', models.BooleanField(default=False)),
                ('is_cash_office_approved', models.BooleanField(default=False)),
                ('payments_made_to', models.CharField(blank=True, max_length=300)),
                ('payments_date', models.DateField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_updated', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='expenditure_department', to='acl.srrsdepartment')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='requisition_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"expenditure"."expenditures"',
            },
        ),
        migrations.CreateModel(
            name='StatusChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=255)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('action_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='expenditure_action_by', to=settings.AUTH_USER_MODEL)),
                ('expenditure', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='status_change_expenditure_instance', to='expenditure.expenditurerequest')),
            ],
            options={
                'db_table': '"expenditure"."status_change"',
            },
        ),
        migrations.CreateModel(
            name='PlatformAdmin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='ACTIVE', max_length=255)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='expenditure_admin', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='expenditure_admin_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"expenditure"."platform_admins"',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note', models.TextField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='expenditure_note_by', to=settings.AUTH_USER_MODEL)),
                ('expenditure', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='note_expenditure_instance', to='expenditure.expenditurerequest')),
            ],
            options={
                'db_table': '"expenditure"."notes"',
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document', models.FileField(upload_to='documents/expenditures')),
                ('file_name', models.CharField(db_index=True, max_length=500)),
                ('file_type', models.CharField(db_index=True, default='Supporting Document', max_length=255)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('expenditure', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='expenditure_document', to='expenditure.expenditurerequest')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='expenditure_document_uploaded_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"expenditure"."documents"',
            },
        ),
        migrations.AddIndex(
            model_name='expenditurerequest',
            index=models.Index(fields=['department', 'status'], name='expenditure_departm_87d229_idx'),
        ),
        migrations.AddIndex(
            model_name='expenditurerequest',
            index=models.Index(fields=['requested_by', 'date_created'], name='expenditure_request_785d1d_idx'),
        ),
        migrations.AddIndex(
            model_name='expenditurerequest',
            index=models.Index(fields=['invoice_number'], name='expenditure_invoice_dfbfb7_idx'),
        ),
        migrations.AlterIndexTogether(
            name='expenditurerequest',
            index_together={('department', 'status'), ('requested_by', 'date_created')},
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['expenditure', 'is_deleted'], name='documents_expendi_5e9cfb_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['uploaded_by', 'date_created'], name='documents_uploade_fff90e_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['file_type'], name='documents_file_ty_4b3ae1_idx'),
        ),
        migrations.AlterIndexTogether(
            name='document',
            index_together={('uploaded_by', 'date_created'), ('expenditure', 'is_deleted')},
        ),
    ]
