# Generated by Django 4.2.1 on 2025-10-30 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenditure', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenditurerequest',
            name='is_deleted',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='expenditurerequest',
            index=models.Index(fields=['is_deleted'], name='expenditure_is_dele_e08427_idx'),
        ),
    ]
