# Generated by Django 4.2.1 on 2026-02-12 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenditure', '0002_expenditurerequest_is_deleted_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenditurerequest',
            name='requires_ceo_approval',
            field=models.BooleanField(default=False),
        ),
    ]
