# Generated by Django 4.2.1 on 2026-02-18 07:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('shift_type', models.CharField(choices=[('MORNING', 'MorMORNINGning'), ('EVENING', 'EVENING'), ('NIGHT', 'NIGHT')], max_length=20)),
                ('radiologist_on_call', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('DRAFT', 'DRAFT'), ('AWAITING_CONFIRMATION', 'AWAITING CONFIRMATION'), ('COMPLETED', 'COMPLETED')], default='DRAFT', max_length=30)),
                ('signed_out_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('incoming_officer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incoming_shifts', to=settings.AUTH_USER_MODEL)),
                ('outgoing_officer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='outgoing_shifts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"radiology"."shifts"',
            },
        ),
        migrations.CreateModel(
            name='TrackNotification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipients', models.JSONField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='shift_model', to='radiology.shift')),
            ],
            options={
                'db_table': '"radiology"."track_notifications"',
            },
        ),
        migrations.CreateModel(
            name='StockEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=255)),
                ('opening_stock', models.PositiveIntegerField()),
                ('closing_stock', models.PositiveIntegerField()),
                ('used', models.PositiveIntegerField(editable=False)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_entries', to='radiology.shift')),
            ],
            options={
                'db_table': '"radiology"."stock_entries"',
            },
        ),
        migrations.CreateModel(
            name='RoomStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('room_type', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('OPERATIONAL', 'OPERATIONAL'), ('CLOSED', 'CLOSED'), ('MAINTENANCE', 'MAINTENANCE'), ('CLEANING', 'CLEANING')], max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='radiology.shift')),
            ],
            options={
                'db_table': '"radiology"."room_status"',
            },
        ),
        migrations.CreateModel(
            name='PlatformAdmin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='ACTIVE', max_length=255)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='radiology_admin', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='radiology_admin_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"radiology"."platform_admins"',
            },
        ),
        migrations.CreateModel(
            name='PendingCase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_identifier', models.CharField(max_length=255)),
                ('examination', models.CharField(max_length=255)),
                ('priority', models.CharField(choices=[('ROUTINE', 'ROUTINE'), ('URGENT', 'URGENT'), ('EMERGENCY', 'EMERGENCY')], max_length=20)),
                ('reason', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_cases', to='radiology.shift')),
            ],
            options={
                'db_table': '"radiology"."pending_cases"',
            },
        ),
        migrations.CreateModel(
            name='NurseHandover',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hazmat_checklist_status', models.BooleanField(default=False)),
                ('spill_kit_status', models.BooleanField(default=False)),
                ('booked_procedures', models.TextField(blank=True)),
                ('concerns', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shift', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nurse_handover', to='radiology.shift')),
            ],
            options={
                'db_table': '"radiology"."nurse_handover"',
            },
        ),
        migrations.CreateModel(
            name='InfectionControl',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cleaning_checklist', models.BooleanField(default=False)),
                ('temperature_checks', models.BooleanField(default=False)),
                ('equipment_disinfection', models.BooleanField(default=False)),
                ('hazmat_issue', models.BooleanField(default=False)),
                ('hazmat_details', models.TextField(blank=True)),
                ('shift', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='infection_control', to='radiology.shift')),
            ],
            options={
                'db_table': '"radiology"."infection_control"',
            },
        ),
        migrations.CreateModel(
            name='EquipmentStatus',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('equipment_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('OK', 'OK'), ('FAULTY', 'FAULTY')], max_length=20)),
                ('remarks', models.TextField(blank=True)),
                ('escalated', models.BooleanField(default=False)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment', to='radiology.shift')),
            ],
            options={
                'db_table': '"radiology"."equipment_status"',
            },
        ),
        migrations.CreateModel(
            name='CriticalResult',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('patient_identifier', models.CharField(max_length=255)),
                ('findings', models.TextField()),
                ('physician_notified', models.CharField(max_length=255)),
                ('notified_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('feedback', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='critical_results', to='radiology.shift')),
            ],
            options={
                'db_table': '"radiology"."critical_results"',
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('details', models.JSONField(blank=True, null=True)),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='radiology.shift')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"radiology"."audit_logs"',
            },
        ),
    ]
