# Generated by Django 4.2.1 on 2026-02-20 08:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('radiology', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='radiologist_on_call',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='radiologist_on_call_shifts', to=settings.AUTH_USER_MODEL),
        ),
    ]
