# Generated by Django 4.2.1 on 2025-02-03 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0002_rename_expiry_out_contract_expiry_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='previous',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
