# Generated by Django 4.2.1 on 2025-02-04 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_alter_contract_previous'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_type',
            field=models.CharField(default='contract', max_length=255),
        ),
    ]
