# Generated by Django 4.2.1 on 2025-02-04 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0004_document_file_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='is_expired',
            field=models.BooleanField(default=False),
        ),
    ]
