# Generated by Django 4.2.1 on 2025-10-13 13:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('acl', '0022_user_cadre_user_systemusers_cadre_a04bb3_idx'),
        ('ict_helpdesk', '0007_document'),
        ('mms', '0011_quote_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uid', models.CharField(db_index=True, max_length=50, unique=True)),
                ('status', models.CharField(db_index=True, default='SUBMITTED', max_length=255)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='documents/security_helpdesk/attachments/')),
                ('issue', models.TextField()),
                ('subject', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('telephone', models.CharField(blank=True, max_length=255, null=True)),
                ('is_acknowledged', models.BooleanField(db_index=True, default=False)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('date_assigned', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('date_completed', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('date_reopened', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('date_closed', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='security_helpdesk_assigned_to', to=settings.AUTH_USER_MODEL)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='security_helpdesk_closed_by', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='security_helpdesk_created_by', to=settings.AUTH_USER_MODEL)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='security_helpdesk_department', to='acl.srrsdepartment')),
                ('facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='security_helpdesk_facility', to='ict_helpdesk.facility')),
            ],
            options={
                'db_table': '"security_helpdesk"."issues"',
            },
        ),
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('expected_closure', models.IntegerField()),
                ('numbering', models.IntegerField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': '"security_helpdesk"."priority"',
                'ordering': ['numbering'],
            },
        ),
        migrations.CreateModel(
            name='StatusChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=255)),
                ('status_for', models.CharField(blank=True, max_length=255, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('action_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='security_helpdesk_action_by', to=settings.AUTH_USER_MODEL)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='security_status_change_issue_instance', to='security_helpdesk.issue')),
            ],
            options={
                'db_table': '"security_helpdesk"."status_changes"',
            },
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='security_quote_issue_instance', to='security_helpdesk.issue')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='security_mmd_quote_issue_instance', to='mms.quote')),
            ],
            options={
                'db_table': '"security_helpdesk"."quotes"',
            },
        ),
        migrations.CreateModel(
            name='PlatformAdmin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='ACTIVE', max_length=255)),
                ('is_hod', models.BooleanField(default=False)),
                ('is_slt', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='security_helpdesk_admin', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='security_helpdesk_admin_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"security_helpdesk"."platform_admins"',
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note', models.TextField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='security_note_issue_instance', to='security_helpdesk.issue')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='security_helpdesk_note_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"security_helpdesk"."notes"',
            },
        ),
        migrations.AddField(
            model_name='issue',
            name='priority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='security_helpdesk_priority', to='security_helpdesk.priority'),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document', models.FileField(upload_to='documents/security_helpdesk/uploads/')),
                ('file_name', models.CharField(max_length=500)),
                ('file_type', models.CharField(max_length=255)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='security_ticket_documents', to='security_helpdesk.issue')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='security_ticket_document_uploaded_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"security_helpdesk"."documents"',
            },
        ),
        migrations.CreateModel(
            name='Assignees',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='security_issue_assigned_by', to=settings.AUTH_USER_MODEL)),
                ('assignee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='security_issue_assignee', to=settings.AUTH_USER_MODEL)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='security_assignee_issue_instance', to='security_helpdesk.issue')),
            ],
            options={
                'db_table': '"security_helpdesk"."assignees"',
            },
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['status'], name='issues_status_ba6d29_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['assigned_to', 'status'], name='issues_assigne_7ac260_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['priority'], name='issues_priorit_9c9cdf_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['department'], name='issues_departm_75a380_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['date_created'], name='issues_date_cr_3acefe_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['is_deleted'], name='issues_is_dele_1a068e_idx'),
        ),
        migrations.AddIndex(
            model_name='issue',
            index=models.Index(fields=['is_acknowledged'], name='issues_is_ackn_d30133_idx'),
        ),
        migrations.AlterIndexTogether(
            name='issue',
            index_together={('department', 'status'), ('assigned_to', 'status'), ('priority', 'status')},
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['issue'], name='security_issue_idx'),
        ),
    ]
