# Generated by Django 4.2.1 on 2025-07-21 12:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ict_helpdesk', '0002_alter_assignees_assigned_by_alter_assignees_assignee'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cancellation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('invoice_no', models.CharField(max_length=255)),
                ('action', models.CharField(max_length=255)),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='PENDING', max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cancellation_created_by', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ict_helpdesk_cancellation_facility', to='ict_helpdesk.facility')),
            ],
            options={
                'db_table': '"invoice_tracking"."cancellation"',
            },
        ),
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('weigh_bill_no', models.CharField(max_length=255)),
                ('courier', models.CharField(max_length=255)),
                ('collector', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, null=True)),
                ('status', models.CharField(default='PENDING', max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('received_on', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tracking_created_by', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ict_helpdesk_tracking_facility', to='ict_helpdesk.facility')),
            ],
            options={
                'db_table': '"invoice_tracking"."tracking"',
            },
        ),
        migrations.CreateModel(
            name='TrackingStatusChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=255)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('action_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='tracking_action_by', to=settings.AUTH_USER_MODEL)),
                ('tracked', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='status_change_tracked_instance', to='invoice_tracking.tracking')),
            ],
            options={
                'db_table': '"invoice_tracking"."tracking_status_change"',
            },
        ),
        migrations.CreateModel(
            name='PlatformAdmin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(default='ACTIVE', max_length=255)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='psd_admin', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='psd_admin_created_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"invoice_tracking"."platform_admins"',
            },
        ),
        migrations.CreateModel(
            name='CancellationStatusChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=255)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('action_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cancellation_action_by', to=settings.AUTH_USER_MODEL)),
                ('cancelled', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='status_change_cancelled_instance', to='invoice_tracking.cancellation')),
            ],
            options={
                'db_table': '"invoice_tracking"."cancellation_status_change"',
            },
        ),
    ]
