# Generated by Django 4.2.1 on 2025-07-29 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_tracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancellation',
            name='type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
