# Generated by Django 4.2.1 on 2025-08-05 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_tracking', '0002_cancellation_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cancellation',
            name='uid',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='tracking',
            name='uid',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
