# Generated by Django 4.2.1 on 2025-08-05 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_tracking', '0003_cancellation_uid_tracking_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='platformadmin',
            name='is_approver',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='platformadmin',
            name='is_receiver',
            field=models.BooleanField(default=False),
        ),
    ]
