# Generated by Django 4.2.1 on 2025-08-12 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_tracking', '0004_platformadmin_is_approver_platformadmin_is_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracking',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
