# Generated by Django 4.2.1 on 2025-11-18 13:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('ict_helpdesk', '0007_document'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invoice_tracking', '0005_tracking_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentralArchive',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uid', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('invoice_no', models.CharField(max_length=255)),
                ('approval_type', models.CharField(max_length=255)),
                ('corporate', models.CharField(max_length=255)),
                ('patient_names', models.CharField(max_length=255)),
                ('date_of_service', models.DateField()),
                ('status', models.CharField(default='UPLOADED', max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='archive_created_by', to=settings.AUTH_USER_MODEL)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='ict_helpdesk_archive_facility', to='ict_helpdesk.facility')),
            ],
            options={
                'db_table': '"invoice_tracking"."central_archive"',
            },
        ),
        migrations.CreateModel(
            name='CentralArchiveStatusChange',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=255)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('action_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='archive_action_by', to=settings.AUTH_USER_MODEL)),
                ('central_archive', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='status_change_archive_instance', to='invoice_tracking.centralarchive')),
            ],
            options={
                'db_table': '"invoice_tracking"."archive_status_change"',
            },
        ),
    ]
