# Generated by Django 4.2.1 on 2025-11-18 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('invoice_tracking', '0006_centralarchive_centralarchivestatuschange'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document', models.FileField(upload_to='documents/archives')),
                ('file_name', models.CharField(db_index=True, max_length=500)),
                ('file_type', models.CharField(db_index=True, default='Supporting Document', max_length=255)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('archive', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='archive_document', to='invoice_tracking.centralarchive')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='archive_document_uploaded_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': '"invoice_tracking"."documents"',
                'indexes': [models.Index(fields=['archive', 'is_deleted'], name='documents_archive_5e819f_idx'), models.Index(fields=['uploaded_by', 'date_created'], name='documents_uploade_fff90de_idx'), models.Index(fields=['file_type'], name='documents_file_ty_4b3ax1_idx')],
                'index_together': {('archive', 'is_deleted'), ('uploaded_by', 'date_created')},
            },
        ),
    ]
