# Generated by Django 4.2.1 on 2024-08-19 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sss', '0002_remove_staff_time_of_leaving_dept'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medical',
            name='is_fit_to_work',
        ),
    ]
