# Generated by Django 4.2.1 on 2024-08-19 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sss', '0004_medical_is_fit_to_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medical',
            name='is_fit_to_work',
            field=models.CharField(default='YES', max_length=5),
        ),
    ]
