# Generated by Django 4.2.1 on 2024-08-20 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sss', '0005_alter_medical_is_fit_to_work'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medical',
            name='days',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medical',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medical',
            name='resume_work_on',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='medical',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='refer',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='refer',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
