# Generated by Django 4.2.1 on 2024-08-20 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sss', '0007_alter_refer_consultant_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medical',
            name='days',
            field=models.IntegerField(default=0),
        ),
    ]
