# Generated by Django 4.2.1 on 2024-08-23 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sss', '0008_alter_medical_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='ohc',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
