# Generated by Django 4.2.1 on 2024-08-23 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sss', '0011_staff_location_staff_ohc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='ohc',
        ),
    ]
