# Generated by Django 4.2.1 on 2026-02-24 11:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.CharField(db_index=True, max_length=100, unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('employee_no', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('staff_status', models.CharField(db_index=True, default='PERMANENT', max_length=50)),
                ('cadre', models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(db_index=True, default=False)),
                ('is_suspended', models.BooleanField(db_index=True, default=False)),
                ('is_defaultpassword', models.BooleanField(default=True)),
                ('profile_updated', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                'db_table': 'systemusers',
            },
        ),
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('is_deleted', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'facilities',
            },
        ),
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('otp', models.CharField(max_length=50)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'otps',
            },
        ),
        migrations.CreateModel(
            name='Sendmail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.JSONField()),
                ('subject', models.CharField(max_length=500)),
                ('message', models.TextField()),
                ('status', models.CharField(default='PENDING', max_length=55)),
                ('is_html', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'send_mail',
            },
        ),
        migrations.CreateModel(
            name='TrackUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.JSONField()),
                ('app', models.CharField(max_length=255)),
                ('ip', models.CharField(max_length=255)),
                ('uid', models.CharField(blank=True, max_length=255, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'track_user',
            },
        ),
        migrations.CreateModel(
            name='SRRSDepartment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('hr_partner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='srrs_department_hr_partner', to=settings.AUTH_USER_MODEL)),
                ('slt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='srrs_department_slt', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'srrs_departments',
            },
        ),
        migrations.CreateModel(
            name='Slt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='slts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'slts',
            },
        ),
        migrations.CreateModel(
            name='Hods',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hod_department', to='acl.srrsdepartment')),
                ('hod', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hod', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hods',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('hod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='department_hod', to=settings.AUTH_USER_MODEL)),
                ('slt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='departments', to='acl.slt')),
            ],
            options={
                'db_table': 'departments',
            },
        ),
        migrations.CreateModel(
            name='AccountActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('action_time', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='activity_actor', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_account_activity', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'account_activities',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_facility', to='acl.facility'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='srrs_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='srrs_user_department', to='acl.srrsdepartment'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='systemusers_email_54c9df_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['employee_no'], name='systemusers_employe_83d00f_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['staff_status'], name='systemusers_staff_s_c81051_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['cadre'], name='systemusers_cadre_a04bb3_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active'], name='systemusers_is_acti_7cebf1_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_staff'], name='systemusers_is_staf_a67d33_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_suspended'], name='systemusers_is_susp_80077e_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['date_created'], name='systemusers_date_cr_3420c4_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['srrs_department'], name='systemusers_srrs_de_e6da4a_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['facility'], name='systemusers_facilit_1dbd64_idx'),
        ),
    ]
