# Generated by Django 4.2.1 on 2024-03-16 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acl', '0002_alter_user_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_defaultpassword',
            field=models.BooleanField(default=True),
        ),
    ]
