# Generated by Django 4.2.1 on 2024-03-18 08:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('acl', '0003_user_is_defaultpassword'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sendmail',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.JSONField()),
                ('subject', models.CharField(max_length=500)),
                ('message', models.TextField()),
                ('status', models.CharField(default='PENDING', max_length=55)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'send_mail',
            },
        ),
    ]
