# Generated by Django 4.2.1 on 2024-03-22 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acl', '0004_sendmail'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='employee_no',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
