# Generated by Django 4.2.1 on 2024-06-05 17:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('acl', '0007_department_hod'),
    ]

    operations = [
        migrations.CreateModel(
            name='SRRSDepartment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('hod', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='srrs_department_hod', to=settings.AUTH_USER_MODEL)),
                ('slt', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='srrs_department_slt', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'srrs_departments',
            },
        ),
    ]
