# Generated by Django 4.2.1 on 2024-06-06 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acl', '0008_srrsdepartment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='srrs_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='srrs_user_department', to='acl.department'),
        ),
    ]
