# Generated by Django 4.2.1 on 2024-07-17 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acl', '0011_ohc_subdepartment'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='ohc',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='srrs_user_ohc', to='acl.ohc'),
        ),
        migrations.AddField(
            model_name='user',
            name='sub_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='srrs_user_sub_department', to='acl.subdepartment'),
        ),
    ]
