# Generated by Django 4.2.1 on 2024-07-18 05:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('acl', '0012_user_ohc_user_sub_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hods',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hod_department', to='acl.srrsdepartment')),
                ('hod', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='hod', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'hods',
            },
        ),
    ]
