# Generated by Django 4.2.1 on 2024-07-18 05:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acl', '0013_hods'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='srrsdepartment',
            name='hod',
        ),
    ]
