# Generated by Django 4.2.1 on 2024-08-14 06:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('acl', '0015_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='srrsdepartment',
            name='hr_partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='srrs_department_hr_partner', to=settings.AUTH_USER_MODEL),
        ),
    ]
