# Generated by Django 4.2.1 on 2025-02-11 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acl', '0016_srrsdepartment_hr_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendmail',
            name='is_html',
            field=models.BooleanField(default=False),
        ),
    ]
