# Generated by Django 4.2.1 on 2025-07-25 09:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('acl', '0017_sendmail_is_html'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('data', models.JSONField()),
                ('app', models.CharField(max_length=255)),
                ('ip', models.CharField(max_length=255)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'track_user',
            },
        ),
    ]
