# Generated by Django 4.2.1 on 2025-07-25 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acl', '0018_trackuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackuser',
            name='uid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
