# Generated by Django 4.2.1 on 2025-09-10 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acl', '0019_trackuser_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='staff_status',
            field=models.CharField(db_index=True, default='PERMANENT', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(db_index=True, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='employee_no',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_suspended',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='systemusers_email_54c9df_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['employee_no'], name='systemusers_employe_83d00f_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['staff_status'], name='systemusers_staff_s_c81051_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_active'], name='systemusers_is_acti_7cebf1_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_staff'], name='systemusers_is_staf_a67d33_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['is_suspended'], name='systemusers_is_susp_80077e_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['date_created'], name='systemusers_date_cr_3420c4_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['srrs_department'], name='systemusers_srrs_de_e6da4a_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['sub_department'], name='systemusers_sub_dep_45fc55_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['ohc'], name='systemusers_ohc_id_ea367b_idx'),
        ),
    ]
