# Generated by Django 4.2.1 on 2025-09-10 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acl', '0020_user_staff_status_alter_user_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profile_updated',
            field=models.BooleanField(default=False),
        ),
    ]
