# Generated by Django 4.2.1 on 2025-09-17 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acl', '0021_user_profile_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cadre',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['cadre'], name='systemusers_cadre_a04bb3_idx'),
        ),
    ]
